### ISSUE TITLE
Multiple buttons after triggering "update_checkout"

### ISSUE THREAD

**Issue by tomwake** [woocommerce/woocommerce-gateway-paypal-express-checkout#479] opened 2018-09-14 11:07 UTC
On the checkout page we have custom logic that uses the update_checkout JavaScript method to refresh the order total.

Due to PayPal Express not checking to see if the buttons are already rendered, new buttons are generated each time the "update_checkout" method is called, e.g. when changing shipping method.

**Comment by menakas** [comment] 2020-01-31 06:50
@tomwake 
Does the problem still persist? It has been more than a year now. 
Please let us know the latest status and also steps to reproduce.

**Comment by menakas** [comment] 2020-02-05 05:33
Closing because
1. there is custom logic involved, 
2. the issue has been logged over an year ago
3. not able to reproduce the issue.

Reopen the issue if it persists.

**Closed by menakas** 2020-02-05 05:33 UTC
Labels: Priority: Low, [Type] Bug
