### ISSUE TITLE
Shipping name overridden with the name on PayPal account

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-paypal-express-checkout#398] opened 2018-03-24 07:51 UTC
### Affected tickets

1021238-zen

### What I expected

To ship the product I purchased to someone else (i.e. as a gift). To do this, I entered a new shipping address on my PayPal buyer account:

![Screenshot](http://cld.wthms.co/SQDOwe+)
Screenshot: http://cld.wthms.co/SQDOwe

### What happened instead. 

Both billing and shipping address in WooCommerce are the address I entered in PayPal - which is expected if I don't require billing address.

However, the shipping name I entered in PayPal has been replaced with the default name set on my PayPal account (in this case, 'test buyer'):

![Screenshot](http://cld.wthms.co/0ZJDDV+)
Screenshot: http://cld.wthms.co/0ZJDDV

### Steps to reproduce

1. Add some products to cart and click the PayPal button on the cart page,
2. Enter a new shipping address with a new first/last name,
3. Confirm the payment - once on the PayPal page and then in WooCommerce,
4. Observe the order in WP Admin and see the shipping name is different than the one you entered.

Reproduced on Pressable, with WC 3.3.4 & PPEC 1.5.2

**Comment by chickenn00dle** [comment] 2020-07-30 01:49
I am not able to reproduce this with the latest versions of WC (4.3.1) and PPEC (2.0.3). Closing.

**Closed by chickenn00dle** 2020-07-30 01:49 UTC
Labels: Priority: Low, [Type] Bug
