### ISSUE TITLE
Adjust nag notification on 'PayPal Express Checkout' plugin

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce-gateway-paypal-express-checkout#192] opened 2016-10-24 06:27 UTC
Originally reported by @simonrcodrington.

Hey guys,

When you run the Woocommerce setup and you choose to add your payment gateways. The '**WooCommerce PayPal Express Checkout Gateway**' plugin adds an undismissable nag notification saying "**PayPal Express Checkout is almost ready. To get started, connect your PayPal account.**" so long as the plugin is installed.

![paypal_woocommerce_nag](https://cloud.githubusercontent.com/assets/12083338/19630884/dc7cea56-99de-11e6-8cff-f13354b1469d.jpg)
That nag notification makes sense when you have the plugin installed **and** activated, however when I just want the plugin activated so I can configure it when I'm ready, it gets in the way on every page. 

Where the notification is defined, it would be great if you guys could set it to be dismissed.  

When I create plugins with conditional important settings; I check to see if the settings have been adjusted and then re-show any applicable notifications. 

Regards

**Comment by simonrcodrington** [comment] 2016-11-05 07:53
Hey guys, just wanted to clarify that the issue is my mind was that even if you don't have the gateway "Enabled", so long as it's installed and activated the nag remains. Basically it seems strange that if the gateway hasn't been "checked" / turned on it still gives you a nag (You've chosen not to use it so until you do it shouldn't nag you).

Thanks guys

**Comment by allendav** [comment] 2017-03-28 14:59
After discussion with the team, we've decided to not make this change. Closing as no plan to fix.

**Comment by galfaroth** [comment] 2017-04-12 10:04
Really!? How to get rid of this nag!

**Comment by simonrcodrington** [comment] 2017-04-13 23:23
That's a real shame this is not going to be adjusted going forward. It's literally as easy as making it a dismissals notice.

Thanks for your consideration though.

**Comment by CaelanStewart** [comment] 2017-05-23 11:58
@allendav, may you please reconsider.

We're building a site for a client using WordPress and WooCommerce.

We specifically do not want to enable PayPal Express Checkout as we are setting up various analytics to record where user's drop off the payment flow, and to track conversions from start to finish.

PayPal Express Checkout makes this task more difficult, therefore we do not wish to enable it.

However, since both the standard PayPal and Express Checkout payments both fall under the same plugin, it is not possible for me to truly disable the Express Checkout method. So now, I'm left with a pointless message that I cannot dismiss.

The client, even with their account with minimalist permissions, will be able to see this message, with no way to dismiss it.

Please explain to me, how even though the payment method is *disabled*, that message is in any way relevant and/or helpful to the client?

**Comment by willwade** [comment] 2017-09-26 10:31
This notification does my nut in. Please change

**Comment by newlocalmedia** [comment] 2017-12-05 22:29
Deactivating the plugin now results in it being reactivated for you and the nag notice reappears. This is *really* annoying.

**Comment by gedex** [comment] 2017-12-07 15:30
Thanks for the feedback everyone! The admin notice should be dismissible in 1.4.7.

**Closed** 2017-12-07 15:29 UTC
Labels: [Pri] Low, [Type] Enhancement
