### ISSUE TITLE
Enabling PayPal Credit overwrites Checkout Payment method title as well as Payment method in order details

### ISSUE THREAD

**Issue by tsetend** [woocommerce/woocommerce-gateway-paypal-express-checkout#630] opened 2019-10-18 11:18 UTC
**Describe the bug**
This issue was reported in this ticket 2426519-zen.

1. When we enable the PayPal Credit, the title for the payment method is overwritten by PayPal Credit:

Screenshot before enabling the PayPal Credit: https://cld.wthms.co/7qzQp1
![Screenshot](https://cld.wthms.co/7qzQp1+)

Screenshot after enabling the PayPal Credit: https://d.pr/ArrXIi
![Screenshot](https://d.pr/ArrXIi+)

Since customers are able to pay using Credit Card as well as PayPal Credit, it will be nice to have the title of the Payment method in checkout not be displayed only as PayPal Credit.

2. Enabling PayPal Credit also overwrites the payment method in order details even when the customer pays using their credit card:

Screenshot without enabling the PayPal Credit: https://cld.wthms.co/ZmOwqi 
![Screenshot](https://cld.wthms.co/ZmOwqi+)

Screenshot after enabling the PayPal Credit: https://cld.wthms.co/Uhxewl
![Screenshot ](https://cld.wthms.co/Uhxewl+)

**To Reproduce**
1. Go to 'WooCommerce > Settings > Payments > Manage PayPal Checkout > Enable PayPal Credit'
2. Add a product to cart and checkout and do a test purchase using a card.
3. You will see that the Title of your payment method in the checkout, as well as order details in email, is changed to PayPal Credit.

**Expected behavior**
I believe this is a bug as mentioned by the customer that PayPal Credit option enabled should not force the description to PayPal Credit when they pay with a credit card. The payment method should follow the actual payment being used.

**Environment (please complete the following information):**
 - WordPress Version 5.2.4
 - WooCommerce Version 3.7.0
 - PayPal Express Checkout Plugin Version 1.6.17
 - Browser [e.g. chrome, safari] and Version Chrome 77.0.3865.120

**Additional context**

**Comment by james-allan** [comment] 2020-01-30 00:50
This is a duplicate of #413. Once the smart buttons are enabled by default in 1.7, this won't be an issue.

**Closed by james-allan** 2020-01-30 00:50 UTC
Labels: Priority: High
