### ISSUE TITLE
Woocommerce 3.62/PayPal Gateway conflict with Wordpress Popular Posts plugin

### ISSUE THREAD

**Issue by essmeier** [woocommerce/woocommerce-gateway-paypal-express-checkout#571] opened 2019-05-15 21:15 UTC
It appears that the Woocommerce 3.6.2 and PayPal Gateway 1.6.11 conflicts with the WordPress Popular Posts plugin, preventing WPP from actively recording stats.

I was running Woocommerce 3.5.8 and Woocommerce PayPal Gateway 1.16.11 and Wordpress Popular Posts 4.2.2.

All worked just fine.

When I upgraded Woocommerce to version 3.6.2, Wordpress Popular Posts quit recording new page visits.

The plugin still works, but new visits aren't recorded or added to the stats.

Reverting to Woocommerce 3.5.8 fixes the problem.  

I initially opened support tickets with the Woocommerce team and the developer of WPP.

They suggested that I migrate to a test site, disable all plugins and enable them one by one.

With only Woocommerce 3.6.2 and WPP active, WPP works fine.

Enabling the PayPal Gateway plugin causes WPP to stop recording stats.

If I disable the PayPal Gateway plugin _or_ revert Woocommerce to 3.5.8, WPP again works correctly.

It's the combination of Woocommerce 3.6.2 _and_ PayPal Gateway 1.6.11 that causes the problem.

Note: Updating the PayPal Gateway to 1.6.14 _does not_ fix this.  
Note 2: Updating Woocommerce to version 3.6.3 _does not_ fix this.

I don't know what to do here.  I've opened a support ticket with the Wordpress Popular Posts developer and I've also opened tickets on the Woocommerce support page and the Woocommerce PayPal Gateway Plugin page.

The latter team suggested that I post this here.  The WPP developer concurred and said he'd follow this thread.

Suggestions?  Wordpress Popular Posts is a fairly popular plugin and a useful one to have functioning on a retail Website.

For now, I've reverted to Woocommerce 3.5.8 and PayPal Gateway 1.6.11 on my live site.  That works, and I'll continue to use those versions until this is resolved.

**Comment by cabrerahector** [comment] 2019-05-15 21:27
Greetings, I'm the developer behind the WordPress Popular Posts plugin.

To add to Charlie's report, here are the links to the topics where this issue has been discussed in detail:

- [Stopped counting stats](https://wordpress.org/support/topic/stopped-counting-stats/)
- [Woocommerce 3.6.2 upgrade breaks WordPress Popular Posts](https://wordpress.org/support/topic/woocommerce-3-6-2-upgrade-breaks-wordpress-popular-posts/)
- [Conflict with PayPal gateway and WordPress Popular Posts](https://wordpress.org/support/topic/conflict-with-paypal-gateway-and-wordpress-popular-posts/)
- [Woocommerce 3.6.2 upgrade breaks WordPress Popular Posts](https://wordpress.org/support/topic/woocommerce-3-6-2-upgrade-breaks-wordpress-popular-posts-2/)

Also, it's worth to note that I wasn't able to reproduce the issue locally with the same setup on a fresh WordPress install so it's clear that this problem is specific to Charlie's site and it can be reproduced easily. Please do read each of the above listed topics to gain some insight.

**Comment by essmeier** [comment] 2019-06-08 21:32
Just created a brand new version of the Website.  I installed Wordpress, Woocommerce, associated Woocommerce plugins and Worpress Popular Posts from scratch.

Using Woocommerce 3.6.4 and PayPal Gateway 1.6.14, along with Wordpress Popular Posts 4.2.2.

With Woocommerce and WPP active, WPP works fine.

When I activate the PayPal Gateway, WPP stops working.  In Chrome tools, I see the error below:

![with_paypal_gateway](https://user-images.githubusercontent.com/50680256/59152505-9c65dd80-8a02-11e9-9755-9a7e92178392.jpg)

**Comment by essmeier** [comment] 2019-06-08 22:37
I should add that Wordpress Popular posts does NOT generate the 403 error when I am logged in.  For logged in users (which would only ever be me,) the plugin works correctly.

For not logged in users, which would be everyone else, it does not work when the PayPal Gateway is enabled.

**Comment by gerbull001** [comment] 2019-10-25 14:25
Hi

I'm having the same issue with the following configuration:

WordPress: 5.2.4

WP Popular Posts: 5.0.0
WooCommerce: 3.7.1
WooCommerce PayPal Checkout Gateway : 1.6.17
No CDN
No Active Caching

The above configuration for logged out user page view breaks the API POST –

( https://XXXX/wp-json/wordpress-popular-posts/v1/popular-posts )

{“code”:”rest_cookie_invalid_nonce”,”message”:”Cookie nonce is invalid”,”data”:{“status”:403}}

If I disable WooCommerce PayPal Checkout Gateway it works

**Comment by essmeier** [comment] 2019-10-25 19:53
Glad to know that I am not alone.  I tested yesterday and upgraded to those same versions and got the same result.

**Comment by essmeier** [comment] 2020-01-08 22:49
Still not working with Woocommerce 3.8.1 and PayPal Checkout Gateway 1.6.18.  Upgraded Wordpress Popular Posts to 5.0.1.

**Comment by menakas** [comment] 2020-01-31 06:24
I tested this.
With WC 3.5.8 and WPP 5.0.2 the view stats are increasing for every visit.
With WC 3.6.0 and WPP 5.0.2 the view stats are constant.

But, I have PPEC deactivated 

I wonder if I have missed something 🤔

@essmeier as you have made the most recent observation, can you please confirm that the enabling or disabling of PPEC has an effect on WPP's working?

**Comment by essmeier** [comment] 2020-01-31 14:10
What is PPEC?

**Comment by LCmry** [comment] 2020-01-31 15:33
Hi @essmeier, I am unable to reproduce this. Here's the steps I used, please let me know if there are any details missing and if you can confirm the same or different results. Thanks!

WordPress 5.3.2
WooCommerce 3.8.1
WordPress Popular Posts 5.0.2
WooCommerce PayPal Checkout Gateway (PPEC) 1.6.18

1. Note counts under **Settings > WordPress Popular Posts** 
2. Visit front end of site as not logged in user
2. With WC and WPP activated visit pages and posts and note increased stats
3. Activate PayPal Checkout Gateway
3. Visit front end of site as not logged in user
4. Visit pages and posts and note increased stats

**Comment by essmeier** [comment] 2020-01-31 18:40
This problem has been going on for nearly a year, and it's been a consistent problem on both my production site and on multiple test sites.

Today I upgraded everything and I'm running:

Wordpress 5.32
Woocommerce 3.9.1
Woocommerce PayPal Checkout Gateway 1.6.18
Wordpress Popular Posts 5.0.2

At the moment, everything seems to be working properly.

Perhaps Hector, the Wordpress Popular Posts creator, can see if it's working for him.

**Comment by cabrerahector** [comment] 2020-01-31 18:52
@essmeier please set up a staging site like you did before (assuming the one you created months ago isn't around anymore) and I'll be glad to do a couple of tests for you.

**Comment by LCmry** [comment] 2020-02-18 18:16
Closing as this appears to be working. Please reopen if this problem persists.

**Closed by LCmry** 2020-02-18 18:16 UTC
Labels: Priority: Low, [Type] Bug
