### ISSUE TITLE
Does not honor WooCommerce Selling/Shipping Locations

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-paypal-express-checkout#235] opened 2017-02-14 20:48 UTC
With Selling Locations set to specific countries, customers from countries not in that list can still checkout.  

**To reproduce** 

1. Use Selling Locations similar to this:

![](http://cld.wthms.co/WTEk/5ToVLDYU+)
_Link to image_: http://cld.wthms.co/WTEk/5ToVLDYU

2. Setup a PayPal account using a country not in that list.  
3. Checkout with PayPal Express Checkout and login using that PayPal account. 
4. Order is allowed to process.

**Comment by FreshPhil** [comment] 2017-02-23 22:03
Another variation to this, is when using "Geolocate" or "Shop Base Address" as the **Default Customer Location**. In that situation, customers can click the Express Checkout button and purchase using PayPal accounts that return an address _not_ within the specific selling locations.
![](http://cld.wthms.co/ZCam/2R2RUzcH+)
Image Link: http://cld.wthms.co/ZCam/2R2RUzcH

**Comment by pcaWeb** [comment] 2017-03-15 16:27
Is there an update on progress with this bug please?

**Comment by allendav** [comment] 2017-03-20 17:16
Will look at this this week or next.

**Comment by allendav** [comment] 2017-04-12 19:54
Fixing this now for 1.2.1

**Comment by allendav** [comment] 2017-04-12 22:08
@mdmoore  @FreshPhil @pcaWeb : So, just to be clear, you're kinda asking for us to interrupt/forbid the purchase _after_ they've initiated checkout with PayPal from their cart, approved the purchase in the PayPal modal (by clicking Continue) and returned to the site?

Because it is only after they are returned to the site do we have access to their shipping address, and that's only true if at least one item in the cart is shippable.  If the items in the cart are virtual items, we won't have a buyer address at all.

So, that's the other concern - virtual products only in the cart - we can't do anything about "sell to specific countries" then at all.

**Comment by FreshPhil** [comment] 2017-04-13 18:14
That's a good point @allendav - I guess we wouldn't be able to fully avoid these situations.
If we could prevent the purchases in the situations where we do get the address, maybe that's the best we can do.

**Comment by allendav** [comment] 2017-04-27 22:54
> I guess there is one flow we could fix - when the buyer initiates checkout from checkout using the paypal mark - they have to fill in their address in checkout anyways then and we could hide the paypal mark if the "only sell to" is not satisfied

Actually, I just confirmed that core WooCommerce doesn't even allow you to enter unsupported countries on the checkout page for billing or shipping addresses (i.e. if you've set "Sell to all countries except..." or "Ship to specific countries only"

**Comment by bor0** [comment] 2017-06-06 06:01
I confirm the same behaviour as @allendav, can't select other country:
![screen shot 2017-06-06 at 08 00 50 am](https://cloud.githubusercontent.com/assets/1620929/26815737/5233b760-4a8e-11e7-8086-64b959ba7e3f.png)

@FreshPhil / @mdmoore can you confirm?

**Comment by FreshPhil** [comment] 2017-06-06 21:41
@allendav & @bor0  - The user doesn't have to specify their country on the checkout page.

After logging into PayPal, they are sent back to WooCommerce were they can simply confirm the order. They don't need to enter their address as it is grabbed from PayPal as you can see here:
http://cld.wthms.co/SPYEKC

**Comment by FreshPhil** [comment] 2017-06-06 21:56
^ In a follow-up to my last comment, when you try the final step of completing the payment WooCommerce kicks in and stops you:

http://cld.wthms.co/XTwSw

Looks like everything is good with the current public version (unless @mdmoore has other input).

**Comment by bor0** [comment] 2017-07-12 09:39
Closing this. Feel free to re-open in case you find any additional issues.

**Closed by bor0** 2017-07-12 09:39 UTC
Labels: [Pri] High, [Status] Needs Author Reply, [Type] Bug
