### ISSUE TITLE
"Cheatin, huh?" in `response` when clicking smart payment for some browsers

### ISSUE THREAD

**Issue by unhammer** [woocommerce/woocommerce-gateway-paypal-express-checkout#582] opened 2019-06-13 20:26 UTC
Version: 1.6.14

I had enabled Smart Payment, which worked fine in my testing on Windows {IE, Chrome, Firefox} and mobile Safari (and Linux {Chrome, Firefox, Opera}), but on Mac OS 10.14, both Chrome 74 and Safari 12 the popup just shows for half a second and then disappears. Chrome's console shows
```
    serialize.js:175 Uncaught Error: Error: TypeError: Cannot read property 'messages' of undefined
        at wc-gateway-ppec-smart-payment-buttons.js?ver=1.6.14:119
        at _loop (promise.js:162)
        at ZalgoPromise._proto.dispatch (promise.js:153)
        at ZalgoPromise._proto.resolve (promise.js:96)
        at promise.js:43
        at XMLHttpRequest.<anonymous> (http.js:117)
        at Object._RECEIVE_MESSAGE_TYPE.<computed> [as postrobot_message_response] (types.js:121)
        at receiveMessage (index.js:114)
        at messageListener (index.js:140)
        at serialize.js:175
        at serialize.js:212
        at util.js:140
        at util.js:102
        at util.js:116
        at replaceObject (util.js:138)
        at util.js:147
        at util.js:109
        at util.js:118
        at replaceObject (util.js:138)
```
(and Safari has basically the same, with longer path names)

Using the debugger, I see that it fails in this line:

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/assets/js/wc-gateway-ppec-smart-payment-buttons.js#L119

and `response` is `Cheatin, huh?` (presumably from https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-cart-handler.php ? Not very helpful message :-/)

-----

(I do see a [CORB](https://www.chromestatus.com/feature/5629709824032768) failure at initial load of the page for the paypal logger, but that's [apparantly fine](https://stackoverflow.com/questions/55558973/getting-cross-origin-read-blocking-corb-error-with-woocommerce-paypal-gateway).)

**Comment by hilaleljamal** [comment] 2019-11-05 03:10
I've got the same problem. It comes only when I enable Litespeed cache, they gave me a script to fix the problem but it only caused the smart button to disappear.

**Comment by menakas** [comment] 2020-01-30 10:29
Closing this as a duplicate of #619. It has some details related to the issue. So, please follow progress there.

**Closed by menakas** 2020-01-30 10:29 UTC
Labels: Priority: High, [Type] Bug
