### ISSUE TITLE
My Account payment process not using PP Checkout UX

### ISSUE THREAD

**Issue by GeoJunkie** [woocommerce/woocommerce-gateway-paypal-express-checkout#801] opened 2020-09-01 20:27 UTC
### Describe the bug
When paying for an order in **My Account > Orders**, the PayPal Standard UX appears, even when it's note active.

### To reproduce

1. Create an order in Pending Payment status
1. Pay for the order using PayPal checkout
1. See the interface used

**Screenshots**

![](https://d.pr/i/CNIEjE+)
Image Link: https://d.pr/i/CNIEjE

Payment methods for above site:

![](https://d.pr/i/yPJ5ZI+)
Image Link: https://d.pr/i/yPJ5ZI

Expected interface:

![](https://d.pr/i/y2PVzD+)
Image Link: https://d.pr/i/y2PVzD

### Expected behavior

The My Accounts page should provide the same UX as Checkout.

**Environment (please complete the following information):**
 - WordPress Version 5.5.1
 - WooCommerce Version  4.4.1
 - PayPal (Express) Checkout Plugin Version 2.0.3
 - Browser [e.g. chrome, safari] and Version Tested on FF 80.0 (64-bit)
 - Any other plugins installed Akismet, Jetpack, WooCommerce Services

### Additional details

[Reported in forums](https://wordpress.org/support/topic/paypal-checkout-is-not-working-when-payment-made-manually-from-my-account-page/).

<details><summary>System status</summary>
  
  ```
`
### WordPress Environment ###

WordPress address (URL): https://tacoppcheckout.mystagingwebsite.com
Site address (URL): https://tacoppcheckout.mystagingwebsite.com
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.21
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.71.1
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_
Total Database Size: 2.70MB
Database Data Size: 1.24MB
Database Index Size: 1.46MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.22MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 7
post: 1
product: 18
product_variation: 7
revision: 1
shop_order: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Jetpack by WordPress.com: by Automattic – 8.9
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Services: by Automattic – 1.24.1 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce: by Automattic – 4.4.1

### Inactive Plugins (2) ###

WooCommerce PayPal Express Gateway: by WooThemes / SkyVerge – 3.7.2 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Square: by WooCommerce – 2.2.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 20
Oldest: 2020-08-12 16:32:51 +0000
Newest: 2020-09-01 20:18:00 +0000

`
  ```
</details>

**Comment by jorgeatorres** [comment] 2021-05-26 19:06
@GeoJunkie: Thanks for the report! Marking as duplicate of #863.

**Closed as completed by jorgeatorres** 2021-05-26 19:06 UTC
