### ISSUE TITLE
The product image set is not working.

### ISSUE THREAD

**Issue by runningjohan** [woocommerce/woocommerce-gateway-paypal-express-checkout#357] opened 2017-12-18 06:29 UTC
After the update the product image set is not working.

Meaning that when I click on the product image set and chose the image the selected image is not showing on the productpage...

I de-activate the pluging and problem solved...

So please fix this problem soon !

**Comment by mattyza** [comment] 2018-01-02 12:12
Hi @runningjohan.

Thank you for your request here.

Would you mind please providing step by step instructions for reproducing the product you're testing with? The payment gateway and product images shouldn't ever interact, so this sounds like quite an irregular issue.

I'd suspect that there is a JavaScript conflict on the page you're loading on the frontend of your store. This is most likely causing the image zoom JavaScript to break.

Thanks in advance.

**Comment by hennroja** [comment] 2018-01-04 22:21
I can confirm that verison 1.4.7 works but 1.5.0 does not !!!

> Coming Soon Page & Maintenance Mode by SeedProd | Version 5.0.17
> Contact Form 7 | Version 4.9.2
> File Manager | Version 5.0.1
> German Market | Version 3.5
> Google Analytics for WordPress by MonsterInsights | Version 6.2.6
> Master Slider | Version 3.3.4
> Naturix Shortcodes | Version 1.0
> Newsletter | Version 5.1.6
> One Click Demo Import | Version 2.4.0
> OptionTree | Version 2.6.0
> Page Builder by SiteOrigin | Version 2.5.16
> Redux Framework | Version 3.6.7.7
> registered-users-only-2 | Version 0.3
> shipcloud für WooCommerce | Version 1.6.1
> SiteOrigin Widgets Bundle | Version 1.11.2
> Slider Revolution | Version 5.4.1
> SVG Support | Version 2.3.11
> TinyMCE Advanced | Version 4.6.7
> UPS (BASIC) WooCommerce Shipping | Version 1.2.8
> WooCommerce | Version 3.2.5
> WooCommerce Category Banner | Version 1.1.2
> Woocommerce customer delivery date time selection | Version 1.1
> Woocommerce customer delivery date time selection | Version 1.1
> WooCommerce PayPal Express Checkout Gateway | Version 1.4.7
> Woocommerce Shipping Options | Version 1.0
> WooCommerce Stripe Gateway | Version 3.2.3
> WooCommerce Subscriptions | Version 2.2.10
> WordPress Importer | Version 0.6.3
> WP-invites | Version 2.52
> WPBakery Visual Composer | Version 6.12
> YITH WooCommerce Quick View | Version 1.2.2
> YITH WooCommerce Wunschliste | Version 2.1.2

This set of plugin works !

After updating "WooCommerce PayPal Express Checkout Gateway" I was not able to update the feature image.

**Comment by adrfonseca** [comment] 2018-01-07 22:29
I can confirm that with "WooCommerce PayPal Express Checkout Gateway" v1.5.0 it's not possible to update the featured image.
Temporarily disabling the plugin it's the only way to update the featured image of a product.

Please fix this.

**Comment by Kiway-it** [comment] 2018-01-10 09:14
Same problem here, v1.5.0 prevent from setting the featured image

**Comment by runningjohan** [comment] 2018-01-10 09:23
Solution:

1) de-activate the pluging WooCommerce PayPal Express
2) Set a featured image in your product page
2) re-activate the pluging WooCommerce PayPal Express

and problem solved...

So we hope the plugin builder can fix this problem soon

**Comment by raindanceharvey** [comment] 2018-02-09 12:10
Having the same problem here. V1.51

Is there a fix yet?

**Comment by sitiwebitalia** [comment] 2018-03-01 05:56
Have the same problem, with WooCommerce PayPal Express (1.4.3) work, but WooCommerce PayPal Express (1.5.3) not work feature image in woocommerce.

**Comment by laurendavissmith** [comment] 2018-03-01 15:24
@sitiwebitalia We just merged an issue into master late yesterday that should resolve this issue since it looks like we have duplicate issues for this.

#376 is the issue that was closed

**Comment by johndcoy** [comment] 2018-03-19 15:36
Can confirm, current master fixes the issue.

**Closed by johndcoy** 2018-03-19 15:36 UTC
Labels: [Status] Needs Author Reply, [Type] Help Request
