### ISSUE TITLE
Rounding Issue

### ISSUE THREAD

**Issue by lolosland** [woocommerce/woocommerce-gateway-paypal-express-checkout#678] opened 2020-02-10 07:05 UTC
Hey Everyone,

this is kind of more of a question/request.

Is there a way we can integrate the following:
1. To send the line items as usual but:
2. To not actually **round** the prices?

I understand why you guys have been rounding the numbers until now but I believe if we stopped rounding them and instead just limit the decimals to what is set in the WooCommerce we may solve this issue otherwise (because to be frank I think it's causing a few more issues than necessary).

The issues I'm referring to is how the invoices look like in PayPal with the Additional Line Items being generated, this is causing confusion to the shop owners, clients and possible chargeback from the actual clients who will not understand at first hand what is going on (even if they were charged the correct amount!!).

P.S @menakas THANK YOU for solving the discounts issue, I've already implemented it and from my end, it's currently working as expected.

**Comment by LCmry** [comment] 2020-02-18 16:55
Hi @lolosland , thanks for the report. For the issue(s) that you are describing, can you provide steps to reproduce them? This will help us better pinpoint the problems and intentions. Thanks!

**Comment by menakas** [comment] 2020-04-03 04:00
Closing as the issue is not clear.

**Closed by menakas** 2020-04-03 04:00 UTC
Labels: [Status] Needs Author Reply
