### ISSUE TITLE
With PPEC enabled and virtual products, "Optional" tag appears next to billing address fields (country, street address etc.).

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce-gateway-paypal-express-checkout#456] opened 2018-07-19 09:55 UTC
**Issue**

With PPEC enabled and virtual products, "Optional" tag appears next to billing address fields (country, street address etc.).

Even if PPEC option is only presented on the cart page and not on the checkout page, with virtual products, billing address fields are marked optional:

![screenshot](http://cld.wthms.co/XT39yQ+) **Image Link:** http://cld.wthms.co/XT39yQ

This can cause issues if a different payment gateway is chosen.

This doesn't happen if the PPEC plugin is disabled or if the product isn't virtual.

Since PPEC takes the billing/shipping info from the PayPal account of the user anyway and if the product isn't virtual and everything works even if these fields aren't optional - I don't see a reason why the "Optional" labels should be displayed on the checkout page.

**Steps to reproduce**

1. Enable PPEC plugin.
2. Create a simple virtual product.
3. Add the product to cart and head to the checkout page.
4. PPEC plugin can be disabled and the checkout page can be refreshed to see that it is indeed PPEC causing this.
5. With PPEC enabled, the "virtual" checkbox can be un-ticked and the checkout page can be refreshed to see that this is only happening with virtual products.

Might be related to https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/commit/16c8598ac235a26a9a3fcddf348baa000269a1b5 since this wasn't happening with the earlier versions of the plugin, although I don't see the direct evidence in the code.

Adding "Type - bug" and "Priority - high" labels since this behavior can cause other payment gateways to not work properly.

**Comment by lkraav** [comment] 2018-07-19 10:39
Duplicate of https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/426 and people are apparently struggling to solve it.

**Comment by seattlec2** [comment] 2018-07-25 13:35
Thanks for reporting the bug and status. I'm experiencing exactly the same problem with PPEC and am anxiously awaiting the fix!

**Comment by Premmy** [comment] 2018-08-30 20:39
Hi! I am also experiencing this issue but more in the My Account > Addresses > Edit Billing.  Disabling the plugin fixes everything but that is not an options.  Hiding the "optional" with CSS is also not an option as additional coding needs to be done to make the fields required.  Is there an estimate on the fix?

**Comment by melindahelt** [comment] 2019-02-04 16:00
10116869-hc User is unable to use this plugin now due to tax laws. Can we get some eyes/ETA on this issue?

**Comment by melindahelt** [comment] 2019-02-04 16:21
User added: Issue has been introduced in version 1.5.6: Fix – Virtual products cause issues with billing details validation with version 1.5.5 the field labels are set to required...

**Comment by tinkertailordesign** [comment] 2019-07-02 21:35
I am having the same issue. It conflicts with automatic tax calculations as those fields are required for that calculation to function, but if only virtual products exist in cart the plugin switches them to optional. Customers are incorrectly not being charged tax so this is a critical issue for many stores. Hoping for an urgent fix.

**Comment by amandasjackson** [comment] 2019-09-15 20:23
Another report here 2351451-zd

**Comment by yukikatayama** [comment] 2019-10-15 21:56
14783869-hc reported as well

**Comment by dsmithweb** [comment] 2019-12-20 21:32
2575899-zen reporting

**Comment by menakas** [comment] 2020-01-30 10:32
@LCmry 
Please check #625 as a possible duplicate.

**Comment by FreshPhil** [comment] 2020-02-04 18:28
2688305-zen as well.

**Comment by LCmry** [comment] 2020-03-20 15:04
See #697

**Closed by LCmry** 2020-03-20 15:04 UTC
Labels: Many: L, Priority: High, [Type] Bug
