### ISSUE TITLE
Fatal

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-paypal-express-checkout#389] opened 2018-02-20 13:50 UTC
in ticket: 954464-zen we are seeing a fatal for 

```
Call to a member function get() on null in [path_to]/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php on line 704
```

No idea what could be the cause of that (crawler maybe??) and I do not believe that it is the cause of the core problem reported in the ticket but I reckon there should be some sort of conditional to prevent it from fataling.

**Comment by bor0** [comment] 2018-02-26 08:06
This is fixed in a4beabf9. Duplicate of #378.

**Closed by bor0** 2018-02-26 08:06 UTC
Labels: [Pri] Low, [Type] Bug
