### ISSUE TITLE
10413 error

### ISSUE THREAD

**Issue by masterguru9** [woocommerce/woocommerce-gateway-paypal-express-checkout#268] opened 2017-05-29 05:25 UTC
Hi,

10413 error when executing paypal express in-page checkout after applying coupon code on cart page.

We are on The this version:
WooCommerce 3.0.1
PayPal for WooCommerce 1.4.4

Thank you.

**Comment by mattyza** [comment] 2017-05-29 07:44
Hi @masterguru9.

Our latest version of WooCommerce PayPal Express Checkout is version 1.2.1. Based on this, I believe you may be running a different PayPal extension, not developed by WooCommerce.

It seems you're running [this PayPal extension](https://wordpress.org/plugins/paypal-for-woocommerce/). I'd suggest logging this over on their support forums, for their developer's reference.

Thanks and regards,
Matty.

**Comment by masterguru9** [comment] 2017-05-30 01:19
Sorry, I mislabeled the plugin name. Our plugin is WooCommerce PayPal Express Checkout Gateway 1.2.1.

**Comment by bor0** [comment] 2017-06-05 09:38
I wasn't able to reproduce this on latest master. @masterguru9 can you please provide exact reproduction steps or check from the screenshots if there's any step I missed? Thanks!

![screen shot 2017-06-05 at 11 35 50 am](https://cloud.githubusercontent.com/assets/1620929/26778852/53472354-49e3-11e7-8cee-dea092c7de69.png)
![screen shot 2017-06-05 at 11 36 15 am](https://cloud.githubusercontent.com/assets/1620929/26778853/536dbe2e-49e3-11e7-99ab-63a4af679a1d.png)
![screen shot 2017-06-05 at 11 36 31 am](https://cloud.githubusercontent.com/assets/1620929/26778854/5373c594-49e3-11e7-9920-bdffddc09b6c.png)

**Comment by storets** [comment] 2017-06-15 07:11
Hello, I am on behalf masterguru
I will pm to bor0 for our development website information and coupon code.
in-page paypal button works fine without coupon code.

**Comment by starlabssystems** [comment] 2017-07-08 16:56
This issue is happening on our site - https://starlabs.systems

There is an active coupon code that works on laptops - independence

If you need any logs or testing or anything, let me know!

**Comment by bor0** [comment] 2017-07-12 09:43
Hi @starlabssystems, I just tried to reproduce this but I get "This coupon has expired".

**Comment by starlabssystems** [comment] 2017-07-12 09:47
Hi @bor0 
Sorry, coupon is active now

Thanks

**Comment by bor0** [comment] 2017-07-12 09:52
Thanks @starlabssystems I was now able to reproduce it. Can you tell me your PPEC version, and have you tried to see if it works with the latest one?

**Comment by starlabssystems** [comment] 2017-07-12 09:54
WooCommerce PayPal Express Checkout Gateway V1.4.1

Yes, I have tried to last 2 versions, the issue is there for all of them.

**Comment by bor0** [comment] 2017-07-12 10:04
Still wasn't able to reproduce locally. The error we're getting on your site is PayPal returned API error code 10413 - The totals of the cart item amounts do not match order amounts.

I am wondering if you are using any other plugins that might interfere this?

Also if you could tell me your Tax settings so that I can set them locally in order to reproduce it'd be great.

**Comment by starlabssystems** [comment] 2017-07-12 10:07
Did try disabling / removing all CSS possible. The only ones left were:
WooCommerce
PPEC
WooCommerce Composite Products (products can't be bought if this is disabled)

Tax is just set to 20% Europe 0% Rest of the World

**Comment by bor0** [comment] 2017-07-12 10:17
@starlabssystems could you please try creating a simple product and see if the issue is reproducible there? I believe this is due to a conflict with composite products (but still trying to identify root cause)

**Comment by starlabssystems** [comment] 2017-07-12 10:19
Composite products does seem to be the issue

Tried the coupon on this product (https://starlabs.systems/product/bullet-usb/) with the plug-in active and it worked fine. So its the product's themselves, not the plugin.

**Comment by bor0** [comment] 2017-07-12 10:21
Thanks for the help @starlabssystems!

Now I have a few assumptions that I can test in order to find the cause. I believe the totals calculation for composite products is not calculated properly thus resulting in the PP error (cart item amounts mismatch order amounts).

**Comment by starlabssystems** [comment] 2017-07-12 10:52
Okay, sounds good.

Just ran a couple of test's, with the components marked as "Priced Individually" the error occurs. When it is unchecked (so components are free), there is no error. So your theory sounds very likely!

**Comment by bor0** [comment] 2017-07-12 11:05
@starlabssystems thanks for the patience and investigating this with me! I created https://github.com/woocommerce/woocommerce-composite-products/issues/213 so that the issue can be given a look there. Will update this ticket with details.

**Comment by starlabssystems** [comment] 2017-07-12 11:40
Hi


Thanks but can't see the repo for composite products!

________________________________

**Comment by bor0** [comment] 2017-07-12 11:41
It's a private repo. I will post updates here. :)

**Comment by franticpsyx** [comment] 2017-07-12 14:35
Hey @bor0 

CP basically just triggers the addition of some extra items in the cart -- that's pretty much it :) "Priced Individually" doesn't do much on its own -- it simply means those cart items maintain the original price/total values of the associated products -- as if they had been added to the cart on their own.

Did you try to see if the same issue happens when **the same** products are added to the cart "manually"? If its a rounding issue with a specific product then you will get the same mismatch error regardless of whether it was added to the cart _via_ CP or _manually_.

If this happens only with CP, I will also need login details to a staging/test site where the issue happens in order to be able to see the exact conditions under which it happens.

**Comment by starlabssystems** [comment] 2017-07-12 14:41
(If I understand what you wrote correctly)
Added the individual component parts to basket, without the main composite product and no issue.

And I have staging site that can be used?

**Comment by franticpsyx** [comment] 2017-07-12 14:52
@starlabssystems @bor0 Can you share access creds? Would love to have a look!

**Comment by starlabssystems** [comment] 2017-07-12 14:56
Course. 

How should I share them? Not sure how to send a message and would prefer not to share with the world - even if it is just for staging!

**Comment by mattyza** [comment] 2017-07-12 15:00
@starlabssystems - if you wouldn't mind please logging a ticket via https://woocommerce.com/my-account/ and labelling it "For attention: Matty", I can ensure the details reach our team correctly.

**Comment by bor0** [comment] 2017-07-13 09:52
@starlabssystems can you please try applying this patch locally to see if it fixes the issue for you? I had reproduced a similar issue locally (but not using coupons, it was tax related), so I'm curious if it's the same issue you're having:
```
diff --git a/includes/class-wc-gateway-ppec-client.php b/includes/class-wc-gateway-ppec-client.php
index ecafc02..5c69b03 100644
--- a/includes/class-wc-gateway-ppec-client.php
+++ b/includes/class-wc-gateway-ppec-client.php
@@ -476,8 +476,6 @@ class WC_Gateway_PPEC_Client {
                                        $extra_line_item = $this->_get_extra_offset_line_item( $diff );
 
                                        $details['items'][]            = $extra_line_item;
-                                       $details['total_item_amount'] += $extra_line_item['amount'];
-                                       $details['order_total']       += $extra_line_item['amount'];
                                }
                        } else {
                                // Omit line items altogether.
```

**Comment by starlabssystems** [comment] 2017-07-13 09:56
Not sure how to "apply the patch". 

Do I just change these lines in the php file?

`                                        $extra_line_item = $this->_get_extra_offset_line_item( $diff );
 
                                        $details['items'][]            = $extra_line_item;
-                                       $details['total_item_amount'] += $extra_line_item['amount'];
-                                       $details['order_total']       += $extra_line_item['amount'];
                                }
                        } else {
                                // Omit line items altogether.`

Or I can give you FTP access if you let me know you IP?

**Comment by bor0** [comment] 2017-07-13 09:57
Yes, please just try removing those 2 lines from that file:
```
-                                       $details['total_item_amount'] += $extra_line_item['amount'];
-                                       $details['order_total']       += $extra_line_item['amount'];
```

**Comment by starlabssystems** [comment] 2017-07-13 10:04
Removed the 2 lines, error still occurs (on starlabsonline.com website)

**Comment by starlabssystems** [comment] 2017-07-13 16:05
Hi @bor0 @franticpsyx 

An unrelated one and I appreciate this is the wrong repo but, with the composite products, the total price only seems to display with certain themes. Is this a Woo issue or theme author issue?

Cheers

**Comment by starlabssystems** [comment] 2017-07-13 16:14
Sorry, double post but just discovered something else with the PayPal error:
Coupon for Basket Total - no error
Coupon for Product - error

If it helps.........

**Comment by franticpsyx** [comment] 2017-07-13 18:32
> the total price only seems to display with certain themes

The total price is displayed only if the price of a composite product is _non-static_.

**Comment by starlabssystems** [comment] 2017-07-13 18:43
> 

The total price is displayed only if the price of a composite product is non-static.
--
Non-static as in changes anyway - like this: https://starlabs.systems/product/star-labtop/#configuration

**Comment by franticpsyx** [comment] 2017-07-13 18:48
You have some odd CSS that hides it there: `.single-product .product_infos p.price:nth-child(1) { display: none; }`

In general, if it works with Storefront but not with some other theme, then there's an issue with the theme.

**Comment by starlabssystems** [comment] 2017-07-13 19:00
Ah cool thanks. 

Now begins someone who knows nothing about CSS trying to edit it!

**Comment by bor0** [comment] 2017-07-14 11:17
@starlabssystems thank you for your patience and help in attempt to resolve this. There was an issue where the discount wasn't applied to shipping (if applicable), thus resulting in the PP error.

Can you please test on the dev instance you sent us and let me know if all is good? If so, I will include that fix in the next version of PPEC.

**Comment by bor0** [comment] 2017-07-14 11:20
Fixes for this so far: e7a3d072caf10a8616349d87fb941596ccdffb00, 3978a17e4f7ec75a63f99789882e591c72ffe77c.

**Comment by starlabssystems** [comment] 2017-07-14 11:58
Looks all good to me!

Applied to staging site.

Thanks very much for your help!

**Comment by starlabssystems** [comment] 2017-07-14 18:54
Slightly stumped but its not working anymore...

Copied the updated php file to the proper site and it didn't work. Went back to staging as it wasn't working either.

Have double checked the changes you had made and they are definitely in place.

Nothing else has been changed so doesn't make sense...

**Comment by mattyza** [comment] 2017-07-15 08:55
Re-opening this for your attention, @bor0.

**Comment by bor0** [comment] 2017-07-17 08:55
Introduced another fix for this: 357fdb7ec1c17dbeec792ab11188bd448cbaa987.

@starlabssystems I changed it directly on your staging site in order to be able to test, and it seems it's fine now. We had 2 separate functions that were doing the same calculation but one of them wasn't updated with the new discounts code fix that I did so I abstracted the calculation into a single function.

Can you please run some tests again? Thanks!

**Comment by starlabssystems** [comment] 2017-07-17 09:03
Hi @bor0 

Just tried adding this to basket on staging with "woo" discount code and got the error:
https://starlabsonline.com/product/star-labtop/

**Comment by bor0** [comment] 2017-07-17 14:03
@starlabssystems I updated staging, please try to use PR https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/302 to check if it resolves the issue for you. Seems fine to me.

**Comment by starlabssystems** [comment] 2017-07-17 14:23
Independence code works fine

Tried "woo" (10% of basket) and got 11812

**Comment by bor0** [comment] 2017-07-17 14:53
@starlabssystems for which product is that? `Star LabTop` works fine for both `woo` and `independence`

**Comment by starlabssystems** [comment] 2017-07-17 15:01
LabTop Pro - I was just choosing at random!

**Comment by bor0** [comment] 2017-07-17 15:55
@starlabssystems nice catch! One more round of testings please :)

**Comment by starlabssystems** [comment] 2017-07-17 16:04
You win - I can't break it! Even with a 100% discount code 

Thanks again :)

Is it just the same php file which has been changed?

**Comment by bor0** [comment] 2017-07-17 16:14
@starlabssystems we both win. Thank you very much!
Please don't include the codefix in prod yet while my teammates review the code.

**Comment by bor0** [comment] 2017-07-17 18:23
@starlabssystems you can use the same fix for production. That fix will be included in the next release. Thanks!

**Closed** 2017-07-17 18:23 UTC
Labels: [Pri] High, [Status] Has PR, [Type] Bug

**Comment by starlabssystems** [comment] 2017-07-17 18:28
@bor0 Will do. Thanks again for your help.

Do you do the PayPal Pro Hosted plugin too? As I have found a bug with that :)

**Comment by bor0** [comment] 2017-07-17 18:29
Can you please try to create an issue in https://github.com/woocommerce/woocommerce-gateway-paypal-pro-hosted/issues? We can follow up from there.

**Comment by starlabssystems** [comment] 2017-07-17 18:30
Would do but its not visible to me!
