### ISSUE TITLE
Cannot load checkout window after cancelling first payment

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-gateway-paypal-express-checkout#184] opened 2016-09-30 15:40 UTC
WooCommerce PayPal Express Checkout Gateway - Version 1.1.2
WooCommerce - Version 2.6.4
- Add items to cart and checkout using the yellow "Checkout with Paypal" button
- On the Paypal checkout screen, cancel the checkout process
- Once back on the cart, click the Paypal checkout button again

**Expected**
The Paypal checkout screen comes up a second time and allows you to checkout

**Actual**
The second time you click the "Checkout with Paypal" button the usual pop over window does not load. Instead an in-page modal comes up, however it is purely white with no content.

http://cld.wthms.co/6UyL/1juguizq

**Comment by gedex** [comment] 2016-11-22 09:26
I believe this has been fixed in `master`, unable to reproduce. Please reopen if you're able to reproduce with `master`.

**Closed by gedex** 2016-11-22 09:26 UTC
Labels: [Pri] High, [Type] Bug
