### ISSUE TITLE
MiniCart button shows up when cart is empty

### ISSUE THREAD

**Issue by akaleeroy** [woocommerce/woocommerce-gateway-paypal-express-checkout#623] opened 2019-09-27 08:57 UTC
**Describe the bug**
The mini-cart PayPal Checkout button shows even when no products are in the cart. Clicking on it produces an error

**To Reproduce**
1. Go to a page with the mini-cart in the header
2. Hover the mini-cart
3. See _No products in the cart_ (`.woocommerce-mini-cart__empty-message`) followed by the PayPal button

**Expected behavior**
PayPal button shouldn't appear unless there are items in the cart

**Screenshots**
![WooCommerce PayPal smart button appearing in empty mini-cart](https://user-images.githubusercontent.com/4068718/65756269-679aa500-e11d-11e9-83d7-0887b09d8527.png)

**Environment (please complete the following information):**
 - WordPress Version: 5.2.3  
 - WooCommerce Version: 3.7.0  
 - PayPal Express Checkout Plugin Version: 1.6.17  
 - Browser: Chrome 77.0.3865.90  

**Additional context**
Temporary fix from CSS using adjacent sibling selector
```css
.woocommerce-mini-cart__empty-message + .wcppec-cart-widget-spb {
  display: none;
}
```

**Comment by menakas** [comment] 2020-01-28 06:36
@akaleeroy 
I tried reproducing the issue with the same versions of plugins, though not the browser. I am unable to reproduce it. 
Can you please confirm that you still see this issue?

**Comment by james-allan** [comment] 2020-01-28 06:54
@menakas and @akaleeroy, this looks the same as https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/450 which I merged earlier.

**Closed by james-allan** 2020-01-28 06:54 UTC
Labels: Priority: High, [Type] Cannot reproduce
