### ISSUE TITLE
WooCommerce 4.3 Compatibility

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-gateway-paypal-express-checkout#760] opened 2020-06-02 00:30 UTC
Check for compatibility with WC 4.3

**Comment by jorgeatorres** [comment] 2020-06-18 12:59
With WC 4.3 around the corner, I'm changing this to 4.3.

**Comment by jorgeatorres** [comment] 2020-06-30 14:15
Everything seems to be working fine. No errors in log files, payments authorized/captured, etc. Tested master (2631a8bc6433a9a0c857a73a7b887a0986d27eb7) against https://github.com/woocommerce/woocommerce/commit/cf64c40ace5baa6f3ec4cd059312fe42ea366771 (which is basically 4.3.0-rc.2) on WordPress 5.4.2.

Tests performed:

- Check that different display settings work properly (hide methods, context-specific settings override defaults, etc.)
- Check that PayPal Credit is available when not hidden (or the checkbox unchecked). Set the store to a US address and used a VPN located in the US.
- With Payment Action: "Sale"
  - Check that the purchase flow can be started and succeeds when initiated from the product page. Tested the PayPal button, credit/debit cards and Credit (when applicable).
  - Check that the purchase flow can be started and succeeds when initiated from the cart page. Tested the PayPal button, credit/debit cards and Credit (when applicable).
  - Check that the purchase flow can be started and succeeds when initiated from the checkout page. Tested the PayPal button, credit/debit cards and Credit (when applicable).
  - Check that the purchase flow can be started and succeeds when initiated from the mini-cart. Tested the PayPal button, credit/debit cards and Credit (when applicable).
  - (Checkout page) Check that missing fields (phone number, etc.) result in the proper error message. Tested the PayPal button, credit/debit cards and Credit (when applicable).
- The above with Payment Action "Authorize".
  - Additionally, confirmed that capturing the charge by changing the order status resulted in no error and the amount was credited in the merchant's account.

**Comment by jorgeatorres** [comment] 2020-06-30 14:15
As such, I'm going to close this issue for now. With WC's commitment to stability I don't think we're going to see things break at least during the 4.3.x cycle.

**Closed by jorgeatorres** 2020-06-30 14:15 UTC
Labels: [Status] In Progress
