### ISSUE TITLE
Smart payment buttons and manually created orders.

### ISSUE THREAD

**Issue by grig-23** [woocommerce/woocommerce-gateway-paypal-express-checkout#714] opened 2020-04-16 15:28 UTC
### Describe the bug

It is possible to configure PayPal Checkout to show smart payment buttons on the checkout page. User in 2876413-zen says that Venmo (part of smart payment buttons functionality) is available during the regular add to cart process but when an order is created manually from wp-admin, a payment link is sent to a customer and they click that link - those are not there.

### To reproduce

* Configure Paypal Checkout as shown in the screenshots.
* Make sure payment request buttons appear at the checkout page when a product is added to cart in a regular fashion.
* Create an order from wp-admin, set the status to "pending payment" and send the invoice from order actions.
* Click the payment link in the email.
* Payment request buttons are not there.
* A huge bonus is a Venmo app configuration since I'm not 100% sure if Venmo appears on checkout pages or only on product and cart pages. Venmo is only available in the U.S so I couldn't test.

**Screenshots**
Configuration:

<img width="998" alt="Screenshot 2020-04-16 at 17 19 23" src="https://user-images.githubusercontent.com/13084901/79474328-8ce1f880-8006-11ea-8a38-44d41b58fab0.png">

<img width="1000" alt="Screenshot 2020-04-16 at 17 20 31" src="https://user-images.githubusercontent.com/13084901/79474377-98cdba80-8006-11ea-9787-629bc37a8dbd.png">

<img width="998" alt="Screenshot 2020-04-16 at 17 20 58" src="https://user-images.githubusercontent.com/13084901/79474426-a97e3080-8006-11ea-9e55-50683f4f5fa0.png">

<img width="996" alt="Screenshot 2020-04-16 at 17 22 31" src="https://user-images.githubusercontent.com/13084901/79474576-e0544680-8006-11ea-8673-a82cc7018a4b.png">

<img width="992" alt="Screenshot 2020-04-16 at 17 22 49" src="https://user-images.githubusercontent.com/13084901/79474609-ea764500-8006-11ea-9e2b-8e7fecb5eb3f.png">

When a manual order is created, a payment link is sent to a customer and they click that link - those are not there:

<img width="695" alt="Screenshot 2020-04-16 at 17 23 24" src="https://user-images.githubusercontent.com/13084901/79474687-fe21ab80-8006-11ea-9feb-0979271e3de4.png">

### Expected behavior

If smart payment buttons including Venmo are available during regular checkout process when a product is added to cart - they should also be available when an order is created manually.

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - PayPal (Express) Checkout Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by achyuthajoy** [comment] 2020-06-16 11:15
@jorgeatorres Can you take a peek? Since the order is created manually and set to pending payment, the Smart Payment Buttons are not loaded. Can add the smart buttons integration, but the data required to create the payment action doesn't exist on the page.

**Comment by jorgeatorres** [comment] 2021-05-26 16:08
Marking this as a duplicate of #863.

**Closed by jorgeatorres** 2021-05-26 16:08 UTC
Labels: type: bug, type: question
