### ISSUE TITLE
Clicking just outside PayPal button leads to undefined/404 page 

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-paypal-express-checkout#850] opened 2021-01-28 11:22 UTC
### Describe the bug

Clicking within a small area around the PayPal Smart Payment Button redirects the customer to a 404 page. The URL is the same as the product page but `/undefined` is appended.

### To reproduce

1. Enable PayPal Checkout and set credentials
2. Ensure _Checkout on Single Product_ is checked under **Single Product Button Settings**
3. Enable Storefront
4. Go to the product page and click just below the yellow PayPal button above the Debit or credit card button. Notice that the button goes grey then the page redirects to the same page but with `/undefined` appended.
5. Click just below the Debit or credit card button, notice the same.

**Screenshots**

![https://d.pr/i/DkJBSI](https://d.pr/i/DkJBSI+)
Image link: https://d.pr/i/DkJBSI

### Expected behavior

Clicking outside of the button should have zero interaction with the PayPal button.

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - PayPal (Express) Checkout Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

As a note, the area that this happens for changes per theme. In Storefront it is just below the button. The customer in a related interaction had this happen all around the button.

I believe it is related to something in this div:
`div id="woo_pp_ec_button_product" class="wc_ppec_responsive_payment_buttons"`

3690861-zen

**Comment by jorgeatorres** [comment] 2021-02-19 13:24
Hi @dougaitken!

Thanks for the report. I remember being able to reproduce this when it was reported, but I can no longer do.
Given the buttons are rendered by the PayPal JS, this is probably something they fixed on their end. I tested on Chrome, Safari and Firefox and couldn't reproduce the issue anymore.

I'm going to close for now, but feel free to re-open if you are still having trouble.

**Closed as completed by jorgeatorres** 2021-02-19 13:24 UTC
Labels: type: bug, feature: smart payment buttons
