### ISSUE TITLE
Order detail not match in Paypal after apply coupon

### ISSUE THREAD

**Issue by zizsoft** [woocommerce/woocommerce-gateway-paypal-express-checkout#335] opened 2017-11-17 07:22 UTC
after v1.4.4, when apply coupon to order, the discount amount will add into details and then in the total, it would be discount x 2. attached an sample

the amount is $124 in total, and i apply a discount $24.8, it would be $99.20

but you would see, it will first 124 + 24.8 = 148.80
and then 148.80 - 49.6 = 99.20

which is a incorrect.

![untitled](https://user-images.githubusercontent.com/7481912/32935363-d1119b22-cbaa-11e7-807a-ff164366dcf7.png)

**Comment by mattyza** [comment] 2017-11-17 09:11
Hi @zizisoft,

Are there any taxes being sent along with the order? I would assume that the coupon is applying to the order total, with taxes included.

**Comment by zizsoft** [comment] 2017-11-17 10:42
hi mattyza
even i disable tax, it also the same result, seems it is not problem related to tax.

**Comment by mattyza** [comment] 2017-11-20 09:20
@roykho - have you perhaps been able to reproduce this during your tests?

@zizsoft - which version of the WooCommerce Stripe integration are you running, and with which version of WooCommerce?

**Comment by zizsoft** [comment] 2017-11-20 09:29
@mattyza , woocommerce plugin v. 3.2.3, woocommerce paypal express checkout gateway plugin is 1.4.5, i also use 1.4.3 - 1.4.4 also has this problem
but in 1.4.0 it would not have this problem.

**Comment by roykho** [comment] 2017-11-22 01:54
@mattyza I have not tested this extension no only PP Advanced and PP Payflow

**Comment by zizsoft** [comment] 2017-11-24 02:56
any update? as this wrong information shown in paypal cannot match to woocommerce order details which make operation and account department has some confusion.
can put it to a urgent fix on this issue?

**Comment by breadadams** [comment] 2017-12-04 13:21
There's been an update recently @zizsoft - #341 - does this resolve it for you??

**Comment by melindahelt** [comment] 2018-01-30 20:14
hi @mattyza checking in on this issue again.

Have a user zd-930200 where the user is experiencing the same issue when coupons are applied to orders.

WooCommerce 3.2.6, PayPal Express Checkout 1.5.0, taxes are not enabled site wide (no tax is ever charged) and shipping is not enabled site-wide (product is a workshop).

PayPal sent to customer
![](http://cld.wthms.co/bZtQ7r+)Image Link: http://cld.wthms.co/bZtQ7r

Product cost is 25, coupon is for 25% off (6.25) but it's showing duplicated.

In addition, this is what user is seeing in PayPal account:

![](http://cld.wthms.co/tOz29A+)Image Link: http://cld.wthms.co/tOz29A

Same behavior in the first screenshot as above. We are not sure why the discount is showing as shipping. No shipping details are set in PayPal.

**Comment by mikeyarce** [comment] 2018-02-01 18:09
Any news on this yet?

**Comment by FreshPhil** [comment] 2018-02-02 21:07
I was able to confirm the behaviour that @melindahelt  mentioned above.

In PayPal the "Order Details" section is adding the product price to the coupon amount. Then the discount is later doubled to bring the order total back in line.

![](http://cld.wthms.co/cjqpdc+)
Image Link: http://cld.wthms.co/cjqpdc

In this example the product was $17.97 and a 50% discount coupon was applied. You can see at the top that the discount total is actually added to the price. Then later on, under "Shipping Discount" the discount total is duplicated to bring the value back to the proper amount.

Also related, why does the discount show as "Shipping Discount". This coupon did not apply to shipping at all.

**Comment by keninbassart** [comment] 2018-03-30 15:16
@roykho 
Have another user reporting this on 1049913-zen Changed priority as well as this is impacting more users. 

![PPScreen](http://cld.wthms.co/DOywFZ+)

Image Link: http://cld.wthms.co/DOywFZ

![NewOrderemail](http://cld.wthms.co/SzEAV1+)

Image Link: http://cld.wthms.co/SzEAV1

**Comment by laurendavissmith** [comment] 2018-03-30 19:52
@keninbassart Added to our triage queue, we'll likely take a look next week

**Comment by roykho** [comment] 2018-04-12 21:13
Can you @FreshPhil or @keninbassart confirm that although it shows the discount being applied twice, the final total is actually correct? Or are you saying customers are being charged incorrectly due to discount applied twice?

**Comment by keninbassart** [comment] 2018-04-13 10:43
@roykho The final total is charged correctly. The issue is that it's being added as a line item and then subtracted as a shipping discount.

**Comment by zwiesman31** [comment] 2018-05-02 13:13
Another user with the same issue: 1113297-zen

**Comment by geeklore** [comment] 2018-06-10 22:31
Just checking to see if there is any update for 1049913-zen.

**Comment by laurendavissmith** [comment] 2018-06-14 22:28
@geeklore nothing yet but it is in our prioritized queue

**Comment by tommyshellberg** [comment] 2018-08-06 11:08
@woocommerce/extendables any update here?

**Comment by AashikP** [comment] 2018-08-23 14:11
Hello @woocommerce/extendables 

Just pinging here to let you know that the ticket 1113297-zd is back on top of the queue

**Comment by conschneider** [comment] 2018-09-03 16:04
Three times is the charm 😺 . Ping: 🛎 . @woocommerce/extendables

**Comment by spraveenitpro** [comment] 2018-11-06 01:07
Checking again with @woocommerce/extendables  :)

**Comment by muckydog-2** [comment] 2018-11-20 01:33
Tagging on to this thread as I too have the same sort of issue happening. When coupon is applied (using native WC coupon functions), payment through PayPal Checkout displays product at original price, line item offset with value of coupon added, line item offset with $0 value. Subtotal is incorrect. Shipping and Tax lines are correct. Seller discount or charges is double the intended discount, which makes up for the line item offset above. Resulting Total is correct. But it's very confusing for customer. 

If, in PayPal setup, I set Subtotal Mismatch Behavior: Do not send items to PayPal, the confusing Line Item Offset entries are not shown, but now the purchaser does not see the items in the description field.

![screen shot 2018-11-19 at 5 13 51 pm](https://user-images.githubusercontent.com/45186835/48745216-6c4e1d00-ec1f-11e8-9a71-3ea6a1fbf815.png)

![screen shot 2018-11-19 at 5 24 09 pm](https://user-images.githubusercontent.com/45186835/48745381-20e83e80-ec20-11e8-860b-afd2f7895908.png)

**Comment by AashikP** [comment] 2018-11-20 06:07
@woocommerce/extendables Just pinging here to see if we're able to provide an update/ETA regarding the progress on this one for user in 1049913-zen.

**Comment by memerson88** [comment] 2018-12-10 21:49
I also have a "crazy" response from PayPal on a sale item.
![image](https://user-images.githubusercontent.com/45772370/49763676-ef98e680-fc92-11e8-9148-8d46c7d92278.png)
Total cost was $249, PPalshows it $549, with a $300 Shipping Discount!

**Comment by jcnjr** [comment] 2019-01-06 22:03
Glad I'm not the only one experiencing this! Just chiming in to report that the Line Item Amount Offset issue is still occurring for us in multiple stores, for both digital and physical products, with Woocommerce v.3.5.3, WordPress 5.0.2 (multisite), and Woocommerce PayPal Checkout Gateway v. 1.5.6 (only gateway used).

The WC order and receipt emails display the coupon applied properly, while Paypal transaction (for example) applies a $5 charge and then a $10 discount to get the discounted total. First noticed back in May, 2018. Still an issue as of January, 2019 and causing serious bookkeeping headaches when importing Paypal reports into Quickbooks. I'm hoping a resolution is in the works since my first report via the Woocommerce support chat only resulted in, "I don't know...you should contact Paypal."

Screenshots from early occurrences of the issue in May, 2018 (Physical Product):
<img width="649" alt="wc-coupon_paypal" src="https://user-images.githubusercontent.com/6288632/50742052-0875b880-11bb-11e9-829d-b2857492c0b4.png">
<img width="551" alt="wc-coupon_woo" src="https://user-images.githubusercontent.com/6288632/50742053-0875b880-11bb-11e9-8535-85c3046a6b51.png">

More recent screenshots from December, 2018 (Digital Product):
<img width="647" alt="wc-coupon_paypal-2" src="https://user-images.githubusercontent.com/6288632/50742099-85a12d80-11bb-11e9-9f66-37f8f6c68c2b.png">
<img width="534" alt="wc-coupon_woo-2" src="https://user-images.githubusercontent.com/6288632/50742100-8639c400-11bb-11e9-80aa-ea4bac3cfc7e.png">

**Comment by AashikP** [comment] 2019-01-24 11:36
Another report in 9725755-hc. Followup at 1744751-zen where the customer is using coupon and line items are displayed multiple times.

![http://cld.wthms.co/SWwO3H+](http://cld.wthms.co/SWwO3H+)
*Direct Link: http://cld.wthms.co/SWwO3H*

They have configured Subtotal Mismatch behavior to be `Add another line item` in **WooCommerce > Settings > Payment > PayPal Checkout**

**Comment by v18** [comment] 2019-02-15 18:20
Hi @dougaitken - are you still able to repro this?

I'm not able to reproduce this using these steps:

1. Add an item to cart
2. Apply a discount code
3. Click on the yellow 'PayPal' button
4. See the correct price, including the discount
5. Pay with PayPal
6. See that the order went through with the discount correctly.

If you're able to repro with a different set of steps, please list them in detail so we can take a look.

**Comment by treibalen** [comment] 2019-02-24 13:54
Reported in 10675866-hc with WC 3.5.5, WP 5.1 and PPEC 1.6.9.

I have tried to test it with WC 3.5.5, WP 5.0.3 and PPEC 1.6.9, but cannot any longer. My 10 Euro coupon is only listed once:

![https://cld.wthms.co/FOHoiC](https://cld.wthms.co/FOHoiC+) 
Full Size: https://cld.wthms.co/FOHoiC

I don't have immediate access to WP 5.1 right now, will test with it tomorrow

**Comment by dougaitken** [comment] 2019-02-25 12:06
@v18, @treibalen, and myself have all been unable to reproduce this behavior. 

We have tested with and without tax being added. 

Due to the age, I believe this has been resolved but not explicitly tested so I'm going to close this.

Please open a new issue with clear reproduction steps if you come across this error again.

Thanks

**Closed by dougaitken** 2019-02-25 12:06 UTC
Labels: [Pri] High, [Type] Bug
