### ISSUE TITLE
"State is not valid" when at check out via PayPal Express Payment Gateway

### ISSUE THREAD

**Issue by Grubs** [woocommerce/woocommerce-gateway-paypal-express-checkout#262] opened 2017-05-11 02:58 UTC
I've had a few people tell me they are getting a "State is not valid"

This is a screenshot of what is happening.

![state-is-no-valid](https://cloud.githubusercontent.com/assets/10626257/25930368/fd5a0d32-3644-11e7-8cd2-c4b5e47209d9.jpg)
 on our website

I got the customer to update their address in PayPal using the drop down box to select a state. She then tried again and it still happened

I did have this code in the functions.php in my child theme a while back to send the abbreviated states through to us

function rs_customize_woocommerce_states() {
            global $states;

            $states['AU'] = array(
                        'ACT' => __( 'ACT', 'woocommerce' ),
                        'NSW' => __( 'NSW', 'woocommerce' ),
                        'NT'  => __( 'NT', 'woocommerce' ),
                        'QLD' => __( 'QLD', 'woocommerce' ),
                        'SA'  => __( 'SA', 'woocommerce' ),
                        'TAS' => __( 'TAS', 'woocommerce' ),
                        'VIC' => __( 'VIC', 'woocommerce' ),
                        'WA'  => __( 'WA', 'woocommerce' )
            );
            
            // you can find lists of states in WooCommerce plugin directory or in /plugins/woocommerce/i18n/states

            return $states;
}

I then changed it to this and it seemed to fix the problem. But it has now returned again!

function rs_customize_woocommerce_states() {
            global $states;

            $states['AU'] = array(
            'ACT' => __( 'Australian Capital Territory', 'woocommerce' ),
            'NSW' => __( 'New South Wales', 'woocommerce' ),
            'NT'  => __( 'Northern Territory', 'woocommerce' ),
            'QLD' => __( 'Queensland', 'woocommerce' ),
            'SA'  => __( 'South Australia', 'woocommerce' ),
            'TAS' => __( 'Tasmania', 'woocommerce' ),
            'VIC' => __( 'Victoria', 'woocommerce' ),
            'WA'  => __( 'Western Australia', 'woocommerce' )
            );
            
            // you can find lists of states in WooCommerce plugin directory or in /plugins/woocommerce/i18n/states

            return $states;
}

We never had the issue at all before the last plugin updates

**Comment by bor0** [comment] 2017-05-24 10:47
> I've had a few people tell me they are getting a "State is not valid"
Since we do not have clear reproduction steps, I will have to assume this is an issue with WC. I filed https://github.com/woocommerce/woocommerce/issues/15252 in hope the proposal gets into WC core and fixes this issue.

**Comment by bor0** [comment] 2017-05-24 14:02
Issue will be fixed in core [here](https://github.com/woocommerce/woocommerce/issues/15252). Feel free to re-open if it re-occurs.

**Closed by bor0** 2017-05-24 14:02 UTC
Labels: [Pri] High, [Status] In Progress, [Type] Bug

**Comment by julienouellette** [comment] 2017-08-24 15:10
I have the same issue, from Canada for the provinces. Could someone help me please?

**Comment by Grubs** [comment] 2017-08-26 00:15
Hi just had a customer inform me that it is happening again. I'm running all defaults now with no customisation made to the states code
