### ISSUE TITLE
PayPal shipping details override the shipping details entered on the site

### ISSUE THREAD

**Issue by zandyring** [woocommerce/woocommerce-gateway-paypal-express-checkout#239] opened 2017-03-24 18:14 UTC
If a customer has a different (or no) company address filled out on their PayPal account, that information is passed back to WooCommerce on checkout, and in both cases (different format/incorrect or no company address at PayPal) it wipes out the shipping details that the customer has added on the store and replaces them.

As an example, the billing column is as it was entered on the site, and the shipping column is how PayPal passed it back to WooCommerce:
![screen shot 2017-04-01 at 12 56 38 pm](https://cloud.githubusercontent.com/assets/7304712/24580716/b8ce7eca-16da-11e7-9d02-070ae9545ad9.png)

The second can't be read digitally, as that line can't have so many characters.

The company name will also be removed, which means some packages don't arrive at their destination correctly.

ticket ref: 540881

**Comment by allendav** [comment] 2017-04-27 22:26
Hey @zandyring - I am having a devil of a time trying to reproduce this.  Can you reproduce it or ask the merchant to provide additional details?

Please be sure they are testing with at least 1.2.0 now.

Important considerations:
- to get this to happen requires the customer to initiate checkout from the checkout page, right? (because checkout from the cart view doesn't give the customer an opportunity to enter a complete address)
- is this only happening for customers with an account on the merchant's site, or guest buyers too?

When I attempt to enter an special destination address on the checkout page and then proceed to PayPal, PayPal alerts me about the address.  Are they seeing this as well? For example:

<img width="974" alt="screen shot 2017-04-27 at 3 20 02 pm" src="https://cloud.githubusercontent.com/assets/1595739/25506902/e009d560-2b5d-11e7-8efa-123f5b213c07.png">

**Comment by allendav** [comment] 2017-04-27 22:55
I'm going to go ahead and release 1.2.1 and then if/when we can reproduce this we'll consider it for the next release

cc @mattyza

**Comment by zandyring** [comment] 2017-05-01 14:29
@allendav I left a note to the customer last week to be sure they were upgraded (per your comment on the thread), but haven't yet heard back. If they re-surface we'll track it down.

**Comment by FreshPhil** [comment] 2017-06-01 21:58
Hey @allendav 
569506-zd-woothemes

Seems to be related to this and has steps to reproduce. Could you have a look when you have a moment and see if this looks like it's related?

**Comment by bor0** [comment] 2017-06-05 09:34
Was able to reproduce. Note that this is reproducible only on the cart screen, and is not reproducible if you go to the checkout screen and checkout with PayPal from there:
![screen shot 2017-06-05 at 11 24 03 am](https://cloud.githubusercontent.com/assets/1620929/26778475/b19861c2-49e1-11e7-8586-c916ffaed88d.png)

I think the issue is that the function `copy_checkout_details_to_post` is not called at all as far as I debugged. Still investigating.

**Comment by bor0** [comment] 2017-06-08 11:36
Hi,

I was able to reproduce this even on 1.1.2. Namely, the address that's entered in PP gets transferred to WC. However in 569506-zd-woothemes they claim this got broken in 1.2.0 (by `* Fix - Compatibility with WooCommerce 3.0, including ensuring the customer address is saved correctly.`)

I just want to make sure that we're on the same page.

@FreshPhil / @zandyring do you have reproduction steps for this, which I expect to be not reproducible on 1.1.2 but be reproducible on 1.2.0?

**Comment by bor0** [comment] 2017-06-08 11:46
I can't reproduce this on latest master / 1.3.0, even with 569506-zd-woothemes.

@FreshPhil / @zandyring have you perhaps been able to reproduce this, and if so do you have reproduction steps for it?

**Comment by bor0** [comment] 2017-07-17 18:24
Ping @FreshPhil @zandyring.

**Comment by FreshPhil** [comment] 2017-07-18 15:45
@bor0 my ticket ended up being a different issue which I opened in #300 
The original ticket @zandyring had is resolved with no follow up from the customer since `1.2` was released, so this issue can be closed.

**Closed by FreshPhil** 2017-07-18 15:45 UTC
Labels: [Pri] High, [Status] Needs Author Reply, [Type] Bug
