### ISSUE TITLE
Unintended consequence of Hide Funding Method(s)

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-paypal-express-checkout#636] opened 2019-11-12 02:40 UTC
**Describe the bug**

Hiding (or showing) Credit Card payment method results in opposite behavior on the PayPal side of things - that is, if I have hidden 'Credit Card' this results in no icons showing up at checkout (expected) however, this seems to be the only way to be able to pay with a credit card at PayPal without logging in which is the opposite of what I would expect.

**To Reproduce**
1. Set the PPEC settings as shown in this screenshot
![see screen shot](https://cld.wthms.co/NUc0Qh+)
2. add an item to cart, proceed to checkout, press the PayPal button, get a modal
3. That modal prompts me to either login or create an account. It lacks a button to allow a credit card payment.
4. Change the PPEC setting to:
![see screen shot](https://cld.wthms.co/WGeRbB+) 
5. Refresh the checkout page.
6. Press the PayPal button, get a modal.
7. Observe that modal has a button to pay by debit/credit card

**Expected behavior**

opposite.

**Environment (please complete the following information):**
 - WordPress Version 5.2.4
 - WooCommerce Version 3.8.0
 - PayPal Express Checkout Plugin Version 1.6.17
 - Browser [e.g. chrome, safari] and Version Chrome 78.0.3904.87 (Official Build) (64-bit)
 - Any other plugins installed Query Monitor, WooCommerce Square

**Additional context**

**Comment by dcrowe1950** [comment] 2019-11-12 12:40
I've found that if you refresh the page when you first go to the checkout page and then click on the credit card icon you get the modal form and not the on-page form. If I use the on page form, I get the error "PayPal error (10485): You have not approved this transaction on the PayPal website. Please check out again and be sure to complete all steps of the PayPal checkout process.". If I use the modal form everything works as expected.

**Comment by syllie** [comment] 2019-11-12 21:46
@WillBrubaker I believe it is working as intended.

The setting 'Hide Funding Methods' only shows/hides the icon-buttons on the frontend. When you 'show' the funding methods, the 'icons' are actually BUTTONS giving access to each funding method directly, with the PayPal button now serving as 'PayPal' only button (if you have setup the landing page to 'Login (PayPal account login)'.  
![image](https://user-images.githubusercontent.com/1240898/68713497-1756a400-05f2-11ea-80a7-6b02f4ee77a3.png)

When you hide the funding methods, the landing page for PayPal adds, as you noticed - a clear button 'or pay with credit/debit card', still giving access to these payment methods.

I think it is bad UI from PayPal's end the as the icons are actually buttons. My clients do not understand this functionality and can no longer find the 'pay with credit card button. Even adding a text message did not improve the situation.

We have a  lot of customers who pay with CC only, and we have hidden the funding methods (no icon-buttons as they are misunderstood) and switched out Landing Page to 'Billing (Non-PayPal account)' - which shows an option to login to PP, as well as CC form directly (PayPal Guest Checkout).

**Comment by dcrowe1950** [comment] 2019-11-13 03:13
The description of the bug doesn't really address the issue that I am seeing. I am having problems with the on-page PayPal form. When  a customer uses it they get an "PayPal error (10485): You have not approved this transaction on the PayPal website. Please check out again and be sure to complete all steps of the PayPal checkout process." If I disable the credit cards and they use the PayPal modal and select credit card payment it works.
One thing that I have noticed is that when they use the on-page form none of the customer information is pre-filled in. The Country is wrong (should be Canada) and there is no first name of last name.

![on-page-paypal_2](https://user-images.githubusercontent.com/54317591/68729715-56540d80-0590-11ea-8df9-ce66a303c53d.jpg)

 When they use the popup modal the customer information including country is filled in.

![modal-paypal_3](https://user-images.githubusercontent.com/54317591/68729842-ad59e280-0590-11ea-8be3-0a4b80eebfbd.jpg)

The on-page form reacts as if it doesn't get all of the information that PayPal requires to process the order. The form doesn't have any space to enter the address or email address so I'm not sure if that is a problem or not.

**Comment by syllie** [comment] 2019-11-13 03:24
@dcrowe1950 

The issue you encountered may be closer related to #611

**Comment by dcrowe1950** [comment] 2019-11-13 03:30
I thought that was address by allowing you to change the Country. This did work up until last week. Then all of sudden none of my customers could pay with a credit card using the on-page PayPal form. I'd love it if they could go away from the form and just have the buttons go to the PayPal credit card modal like it did in the earlier version (spring).

**Comment by jorgeatorres** [comment] 2021-05-27 13:14
Hi there!

In reference to the original issue: as explained in comment https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/636#issuecomment-553130816, the 'Hide Funding Method(s)' setting only hides certain buttons on the frontend. In the specific case of "Credit Card" it hides the debit/credit card button and form.
Now, what PayPal decides to show once you click the PayPal button is entirely on their side. The plugin has little control over the checkout flow on paypal.com, sadly.

I'm closing this issue now, but freel free to re-open if I've missed something. As for the issues with the country dropdown, those are being handled in #611 and other issues in the repo.

**Closed by jorgeatorres** 2021-05-27 13:14 UTC
Labels: priority: low, type: bug
