### ISSUE TITLE
Error 10413 - amounts mismatch - Issue with Decimal Quantities

### ISSUE THREAD

**Issue by dademaru** [woocommerce/woocommerce-gateway-paypal-express-checkout#430] opened 2018-06-22 08:57 UTC
Hello,

I'm having the following issue with WC PPEC & decimal (float) quantities:

> PayPal error (10413): An error (10413) occurred while processing your PayPal payment. Please contact the store owner for assistance.

I'm using WP 4.9.6, WC 3.4.3, PPEC 1.5.6.
This is what I get in the log:
```
[21-Jun-2018 15:54:24 UTC] WC_Gateway_PPEC_Client::_request: remote request to https://api-3t.sandbox.paypal.com/nvp with params: Array
(
    
    [ADDROVERRIDE] => 1
    [LANDINGPAGE] => Login
    [SOLUTIONTYPE] => Sole
    [PAYMENTREQUEST_0_PAYMENTACTION] => sale
    [PAYMENTREQUEST_0_INSURANCEAMT] => 0
    [PAYMENTREQUEST_0_HANDLINGAMT] => 0
    [PAYMENTREQUEST_0_CUSTOM] => 
    [PAYMENTREQUEST_0_INVNUM] => 
    [PAYMENTREQUEST_0_CURRENCYCODE] => EUR
    [PAYMENTREQUEST_0_AMT] => 188.69
    [PAYMENTREQUEST_0_ITEMAMT] => 144.66
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 10
    [PAYMENTREQUEST_0_TAXAMT] => 34.03
    [PAYMENTREQUEST_0_SHIPDISCAMT] => 0
    [NOSHIPPING] => 0
    [L_PAYMENTREQUEST_0_NAME0] => ###
    [L_PAYMENTREQUEST_0_DESC0] => 
    [L_PAYMENTREQUEST_0_QTY0] => 4.1
    [L_PAYMENTREQUEST_0_AMT0] => 22.6
    [L_PAYMENTREQUEST_0_NAME1] => ###
    [L_PAYMENTREQUEST_0_DESC1] => 
    [L_PAYMENTREQUEST_0_QTY1] => 2.6
    [L_PAYMENTREQUEST_0_AMT1] => 20
    [METHOD] => SetExpressCheckout
    [VERSION] => 120.0
    [USER] => ###
    [PWD] => ###
    [SIGNATURE] => ###
)

[21-Jun-2018 15:54:25 UTC] WC_Gateway_PPEC_Client::_process_response: acknowleged response body: Array
(
    [TIMESTAMP] => 2018-06-21T15:54:25Z
    [CORRELATIONID] => 57538652c866
    [ACK] => Failure
    [VERSION] => 120.0
    [BUILD] => 47201799
    [L_ERRORCODE0] => 10413
    [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => The totals of the cart item amounts do not match order amounts.
    [L_SEVERITYCODE0] => Error
)
```

According to [this answer](https://www.paypal.com/us/smarthelp/article/why-did-i-get-error-10413-%E2%80%9Ctransaction-refused-because-of-an-invalid-argument.-see-additional-error-messages-for-details.-the-totals-of-the-cart-item-amounts-do-not-match-order-amounts%E2%80%9D-ts1990), 

> To resolve this issue, check that the sum of the values equals the value of PAYMENTREQUEST_0_AMT.

But the values are correct:
(4,1 * 22,6) + (2,6 * 20) = 144,66 [PAYMENTREQUEST_0_ITEMAMT]
144,66 + 10 + 34,03 = 188,69 [PAYMENTREQUEST_0_AMT]

Is it possible that there is a issue with **decimal quantities**?
Is PayPal casting **L_PAYMENTREQUEST_0_QTY** to integer and the its calculation fails?
[Here](https://github.com/woocommerce/woocommerce/issues/12554) Mike suggests:
> to enable the filter which sends the order as 1 big item

I suppose he refers to **woocommerce_paypal_args** hook, to set `$force_one_line_item = true` and use [get_line_item_args_single_item](https://github.com/woocommerce/woocommerce/blob/master/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L282).

But I couldn't find a similar hook in your plugin.
Is it possible to “Get line item args for PayPal request as a single line item” with PPEC?

Thanks
Davide

**Comment by dademaru** [comment] 2018-07-05 09:17
Hello,

I've updated to **PPEC 1.6.1** and the issue is still the same.

I can't find any hook to enable '**Do not send line items to PayPal**'  by default (not only for 'Subtotal Mismatch Behavior'), which would fix this issue.

Does anyone know how to force “PayPal request as a single line item“ with this plugin?

Thanks,
Davide

**Comment by Pederzh** [comment] 2018-07-05 10:45
Hello @dademaru 

The problem is with item details: you can unset item details in the function `get_details()` in the file `class-wc-gateway-ppec-client.php`.
As you can see in this function it unsets `$details['items']` if `not('add' === $settings->get_subtotal_mismatch_behavior())` but only if `$details['total_item_amount'] != $rounded_total`.
Your problem has not a different total amount between paypal and woocommerce so just setting in WP Settings>Payments: "Subtotal Mismatch Behavior = Do not send line item to PayPal" it won't resolve your problem.

If you modify the `return $details;` of the function `get_details()`at line 622 with `return apply_filters( 'woocommerce_paypal_express_checkout_get_details', $details );`
You can do `$details['items']` in a custom function used has a filter and it will work.
Example: 
```
add_filter('woocommerce_paypal_express_checkout_get_details', 'my_paypal_force_one_line_item' );
function my_paypal_force_one_line_item( $details ){
	unset( $details['items'] );
	return $details;
}
```

So i think if the plugin creator would add in line 622: `return apply_filters( 'woocommerce_paypal_express_checkout_get_details', $details );` instead of `return $details;` would a nice solution to let devs access this part of plugin.

Hope I helped you
Pederzh

**Comment by dademaru** [comment] 2018-07-09 07:35
Hello @Pederzh 
thanks for the fix!
I hope it will be added to the plugin next release.

**Comment by zwiesman31** [comment] 2018-07-12 14:50
CC: @dechov - Is this something we could look at implementing right away?

**Comment by dechov** [comment] 2018-07-12 20:04
@bor0 I don't think I currently have enough perspective on the overall issue to say if a new filter is the best solution, or if a somewhat different change is warranted, but I don't see why we shouldn't at least get the filter implemented in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/449 into the next release. cc @laurendavissmith @bor0

**Comment by dademaru** [comment] 2018-08-24 08:09
Hello @dechov 
any news on adding this hook?
I can't see it in 2 latest release.
Thanks

**Comment by dademaru** [comment] 2018-10-01 08:43
Hello @zwiesman31 @dechov 
Sorry if I insist but this is just a simple hook, which does not compromise nor change in any way the default behavior of your plugin.
However, in the case of decimal quantities, it would allow the use of PayPal and there would be no need to change the code of your plugin at each release.
I hope you can consider the pull request.
Thanks

**Comment by strarsis** [comment] 2019-10-18 16:05
This is very bad because it prevents customers from finishing a purchase. 😢

**Comment by allendav** [comment] 2019-12-05 21:31
Closing this issue. A hook was added in #449 to ameliorate the problem.

**Closed by allendav** 2019-12-05 21:31 UTC
Labels: Priority: Low, [Type] Bug
