### ISSUE TITLE
Name and address fields marked as optional regardless of checkout option

### ISSUE THREAD

**Issue by justanotherentrepreneur** [woocommerce/woocommerce-gateway-paypal-express-checkout#625] opened 2019-09-30 02:18 UTC
When PayPal Express Checkout Plugin is enabled on my website, First Name, Last Name, and Address details are all marked as "(optional)", regardless of the checkout method (PayPal or Stripe). 

In Settings, I am unable to check "Require Billing Address". Anytime I try and click "Save Changes", the page refreshes and the box is unchecked.

I would like to have First Name, Last Name, and Address required for all customers, regardless of whether they use PayPal or another checkout method. The regular PayPal plugin works flawlessly, but it does not provide PayPal Credit as a checkout option, which is what is forcing me to make PayPal Express Checkout work.

<img width="1494" alt="Screen Shot 2019-09-29 at 7 14 49 PM" src="https://user-images.githubusercontent.com/55966173/65845112-bf880600-e2ed-11e9-94d5-f18c88b74e11.png">

<img width="1170" alt="Screen Shot 2019-09-29 at 7 18 13 PM" src="https://user-images.githubusercontent.com/55966173/65845162-eb0af080-e2ed-11e9-813f-842566eaa7cb.png">

**Comment by zwiesman31** [comment] 2019-12-16 13:59
Another report of this happening on 2554127-zen

CC: @allendav Is there a reason why this is set as an `Enhancement`? Looks like more of a bug to me.

**Comment by menakas** [comment] 2020-01-30 10:32
Possible duplicate of #456.

**Comment by menakas** [comment] 2020-01-30 11:23
Duplicate of #426. Closing this.

**Closed by menakas** 2020-01-30 11:23 UTC
Labels: Priority: Low, [Type] Enhancement
