### ISSUE TITLE
Smart Payment Buttons does not populate PayPal Guest Checkout with billing info.

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce-gateway-paypal-express-checkout#474] opened 2018-08-31 19:01 UTC
Using PayPal Checkout the PayPal Guest Checkout is populated with billing information ( [#](http://cld.wthms.co/LUkEOm) ). When **Smart Payment Buttons** are enabled the data is not pulled from the checkout fields ( [#](http://cld.wthms.co/9fHwNV) ).

**Comment by dechov** [comment] 2018-08-31 19:47
Possible duplicate of https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/448 (if I understood that one correctly)

**Comment by johndcoy** [comment] 2018-08-31 22:45
Hey @dechov , That sounds right but I did confirm this is specific to using the Smart Payment Buttons. I can't confirm if that's the case with that issue.

**Comment by jobthomas** [comment] 2018-09-13 12:52
Another chat with this issue: 6414425-hc

Steps to reproduce:

* Use the smart button
* Choose an address associated with the PayPal account
* The result only returns a shipping and not a billing address

I get redirected to the shop page after choosing an address there:

![http://cld.wthms.co/i6SrDA](http://cld.wthms.co/i6SrDA+)
Link to image here: http://cld.wthms.co/i6SrDA.

(This is reproduced locally)

**Comment by AmberSheppMZ** [comment] 2018-09-13 13:06
This is happening with my website: 
When customers use paypal express to complete their purchase and add a different shipping address, once completed, woocommerce generates an order but changes the billing details to the shipping details too. Any news on when this will be fixed? Thanks!

**Comment by dechov** [comment] 2018-09-13 14:27
@jobthomas This appears to be a different issue – I can test a little later, but do you know if it is specific to Smart Payment Buttons, and if/how the [Require Billing Address](https://docs.woocommerce.com/document/paypal-express-checkout/#section-6) setting affects this?

@AmberSheppMZ Am I understanding correctly that the shipping address selected in the PayPal flow is ignored and the billing address from the PayPal flow is used instead?

**Comment by jobthomas** [comment] 2018-09-13 15:19
@dechov - ah, I thought that this was what @johndcoy  was describing. This is without the required billing address as that's something I'd need permission from PayPal for.

It's specific to the Smart button indeed. Just going through regular checkout doesn't make this happen (because then you'd add the checkout details there in the first place).

**Comment by johndcoy** [comment] 2018-09-13 16:19
Hey @jobthomas I saw a similar request for what you're referring to in the forums. Although the name and email show on the order confirmation page, the full shipping address is recorded after an order is placed. 

https://wordpress.org/support/topic/get-billing-address-from-paypal/

A separate issue/concern still.

**Comment by AmberSheppMZ** [comment] 2018-09-14 08:34
@dechov The shipping address is changed within the paypal flow, but once back on the website, the billing details are also changed to the shipping details even though I never wanted to change the billing details, only the shipping.

**Comment by jobthomas** [comment] 2018-09-14 09:15
@dechov you want me to create the separate issue?

**Comment by dechov** [comment] 2018-09-16 19:27
@jobthomas Sure – thanks! From a brief bit of testing, it looks like it can be reproduced from the Cart page with or without Smart Payment Buttons. The shipping address being copied to the billing address seems like another consequence of the same issue.

**Comment by dechov** [comment] 2018-09-28 18:32
A fix for this is included in the latest release – thanks!

**Comment by hannahswain** [comment] 2018-11-01 11:30
Re-opening this issue. It looks like the fix was included in version `1.6.5`, but I've seen the same issue on both a customer's site and my own test site in 1534922-zen 

Changing from `enhancement` to `bug`, as this is something that should work.

**Comment by dechov** [comment] 2018-11-02 03:42
@hannahswain Thanks – https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/477 is a WIP for passing the **phone** and **email** to PayPal, which we will prioritize in accordance with this report.

The **country** is a different matter, as the value _is_ passed but appears to be ignored in favor of the locale configured on the merchant's end. We can investigate this further, and contact PayPal if necessary.

**Comment by madeincosmos** [comment] 2018-11-03 14:57
One more user reporting this in 1535889-zen

**Comment by hannahswain** [comment] 2018-11-05 11:56
Thanks for the explanation, @dechov ! I'll update the customer in regards to the country.

**Comment by hannahswain** [comment] 2018-11-14 13:30
This came up in the following forum thread: https://wordpress.org/support/topic/problem-with-input-contry-on-norwegian-guest-checkout/

I did a bit of testing, where the language files for each language were installed before testing:

WC site base: Sweden
Site language: English (US)
PayPal guest checkout country: United States

WC site base: Sweden
Site language: Svenska
PayPal guest checkout country: Sweden

WC site base: Sweden
Site language: Norsk bokål
PayPal guest checkout country: United States

Site base: Norway
Site language: Norsk bokål
PayPal guest checkout country: United States

Site base: Norway
Site language: Nederlands
PayPal guest checkout country: Netherlands

It seems that the PayPal guest checkout is picking up on the site language rather than anything else, with the strange exception of Norsk bokmål.

1. Is it intended that PayPal guest checkout is using the site language to determine this?
2. if so, why is Norwegian an exception?

**Comment by LaurenaRehbein** [comment] 2018-11-14 22:17
Also here, for Israel:  1543722-zen

**Comment by dechov** [comment] 2019-08-19 22:41
Between https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/476, https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/477, and https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/482, this issue has been fixed aside from the default country not matching the value in the Checkout form, which is now tracked separately in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/611.

**Closed by dechov** 2019-08-19 22:41 UTC
Labels: [Pri] High, [Type] Bug
