### ISSUE TITLE
Billing phone number required field since new updates

### ISSUE THREAD

**Issue by Jo-TNVA** [woocommerce/woocommerce-gateway-paypal-express-checkout#282] opened 2017-06-10 13:09 UTC
Whenever a guest goes to the checkout and tries to pay with PayPal, the screen is returned with an error saying the billing phone number is a required field. This has never been ticked in the settings but is now returning the error since the updates were done.

My client says he updated WordPress to 4.8 and plugins for PayPal, Stripe and Woocommerce to the latest.

Please help.

![img_2780](https://user-images.githubusercontent.com/29334179/27002989-4faa9c88-4de6-11e7-856c-673d79d33e36.JPG)

**Comment by mattyza** [comment] 2017-06-12 07:40
Hi @Jo-TNVA,
Is the "Billing Address" setting enabled currently, after upgrading to the latest version?

An additional note, if this field is enabled, you'd need to contact PayPal to have this feature enabled on your account.

Thanks in advance for your feedback.

**Comment by Jo-TNVA** [comment] 2017-06-12 08:44
Hi @mattyza 

No, it's never been enabled.
I have 'Send shipping details to PayPal instead of billing' enabled.

Thanks
Jo

**Comment by tommyshellberg** [comment] 2017-06-13 15:53
@mattyza I can also reproduce this error. Billing Phone is *not* required within both my PPEC plugin settings page and my PayPal merchant account(sandbox).

**Comment by mattyza** [comment] 2017-06-14 14:41
Thanks @tommyshellberg. I've assigned to @bor0 for his attention in his next PPEC sprint.

**Comment by tuna-f1sh** [comment] 2017-06-19 13:09
I have this problem too. Is there a work around fix in the mean time? Customers have brought it to my attention as they can't order...

**Comment by jackgregory** [comment] 2017-06-21 17:47
Same here, cant take any orders due to this issue.

**Comment by jackgregory** [comment] 2017-06-21 22:49
@tuna-f1sh 

in the file `includes/class-wc-gateway-ppec-checkout-handler.php` change line 148 to

`$billing_fields['billing_phone']['required'] = 'yes' === $require_phone_number;`

Fixes the issue for me until an update.

**Closed** 2017-06-22 11:14 UTC
Labels: [Pri] CRITICAL, [Status] Has PR, [Type] Bug

**Comment by benjamingibert** [comment] 2017-06-28 14:30
Has an update been released to fix this? It is still stopping my customers from ordering via PayPal?

**Comment by bor0** [comment] 2017-06-28 14:58
Will try to release today/tomorrow.

**Comment by khejduk** [comment] 2017-09-20 17:28
Has this been resolved?

**Comment by electricAlchemy** [comment] 2017-12-22 19:10
I am still having issues with this as well. It looks like maybe the number is sent when I have "Send shipping details to PayPal instead of billing" unchecked, but when it is enabled the phone number does not come through?
