### ISSUE TITLE
Smart Payment Buttons erroring with subscription products

### ISSUE THREAD

**Issue by NickGreen** [woocommerce/woocommerce-gateway-paypal-express-checkout#614] opened 2019-08-23 16:17 UTC
2293488-zd

## Synopsis 

When clicking the credit card buttons, also known as _Smart Payment Buttons_ on the product page results in errors. This is only happening on subscription products (variable and simple). Non-subscription products allow inline checkout functionality for single product page.

## Details

**1. Set up Smart payment buttons**

These are the Smart Button settings that will get these buttons to show up on the single product page. 
![](https://cld.wthms.co/2TALLs+)

**2. Click Smart payment buttons from a subscription product page**

On subscription product page, click Visa, MasterCard, or Discover, to get this error message: 
![](https://cld.wthms.co/I6kqyQ+)

If you click Try Again, the modal PayPal payment information window loads: 
![](https://cdn-std.dprcdn.net/files/acc_862132/RQsZBw)

If you click Amex, the modal payment window loads on the first click. 
![](https://cdn-std.dprcdn.net/files/acc_862132/oheGDi)

We were able to replicate this issue with subscription products. Based on this, I think we may be looking at another version of this bug, or a different but related bug: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/596 

No WC fatal errors logged, no PayPal errors logged.

## Expected behavior
If inline checkout for subscription products isn't supported, this checkout method should default to the modal with no error message.

**Comment by NickGreen** [comment] 2019-08-23 19:36
Note from merchant regarding settings for duplicating the issue:

>  I do not have credit cards funding method hidden, which shows those buttons. I don't know if that would cause any issues with the coding team in resolving this issue.

**Comment by james-allan** [comment] 2020-01-30 00:43
Hey @NickGreen 👋 
I haven't been able to replicate this one. 
 
When I click Visa, MasterCard, or AMEX on a subscription product's single product page, the modal loads without any errors. 

Screencast: https://d.pr/v/BnLPld

Looking at the ticket, I can see you were able to replicate it on your local. Is this error still happening for you?

**Comment by menakas** [comment] 2020-01-30 10:44
I too could not reproduce this behaviour. Any specifics that I may be missing?

**Comment by james-allan** [comment] 2020-01-31 03:11
Given two of us can't replicate it, I'm going to close it. If this is still an issue for someone, please feel free to reopen and provide additional steps to help replicate. 🙂

**Closed by james-allan** 2020-01-31 03:11 UTC
Labels: Feature: Smart Payment Buttons, Priority: High
