### ISSUE TITLE
virtual/downloadable products cause checkout validation to fail

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-paypal-express-checkout#415] opened 2018-05-17 11:39 UTC
ticket: 1158910-zen

1. A product is both virtual and downloadable
2. A terms and conditions page is configured
3. Add the product from step 1 to your cart (with no other products)
4. Go to the cart page
5. Press the PayPal button
6. login to PayPal as required, make the payment
7. You are redirected back to the site to check the 'terms and conditions' box, check it, press the pay for order button
8. See validation errors:
![see screen shot](http://cld.wthms.co/shP4BW+)

**Comment by WillBrubaker** [comment] 2018-05-17 12:16
Seems you can skip step 2 and still reproduce

**Comment by bor0** [comment] 2018-05-30 08:09
Seems like a duplicate of #417. Does it only happen for virtual products?

**Comment by WillBrubaker** [comment] 2018-05-31 20:04
#417 may be a duplicate of this - it does not happen for products that aren't virtual/downloadable (at least not that I could cause).

**Comment by bor0** [comment] 2018-06-05 09:47
OK I see. I updated the description of that other ticket to match and closing this one since we have discussion going on there.

**Closed by bor0** 2018-06-05 09:47 UTC
Labels: [Pri] High, [Type] Bug
