### ISSUE TITLE
Paypal Checkout buttons displayed twice on Checkout Page

### ISSUE THREAD

**Issue by bluestreakdesigns** [woocommerce/woocommerce-gateway-paypal-express-checkout#473] opened 2018-08-31 17:32 UTC
I have plugin version 1.6.3 installed with the latest Woocommerce version.  The plugin works fine for single product pages and the cart page.  However on the checkout page two of each button are being displayed.

![screenshot](https://user-images.githubusercontent.com/27625458/44927338-3b4a0480-ad22-11e8-8bb8-912110eaef54.jpg)

**Comment by bluestreakdesigns** [comment] 2018-09-02 16:00
After investigating it looks like there is a conflict with the Braintree for Woocommerce Pro plugin.  Braintree processes my credit card transactions so its one I cant do without

**Comment by allendav** [comment] 2019-12-05 21:41
I suggest we add a filter to allow suppression of the buttons on the checkout page for this unusual case. Will try to do so in 1.7.1

**Comment by allendav** [comment] 2019-12-05 21:42
Workaround: In the interim, use CSS to hide our buttons on .checkout

**Comment by menakas** [comment] 2020-02-05 05:28
@bluestreakdesigns 
I am unable to reproduce the issue with v 1..6.3 and Braintree for WooCommerce( not Pro, though).
Can you confirm if you still have this issue with version 1.6.18?

**Comment by menakas** [comment] 2020-04-03 04:30
Cannot reproduce. Closing...

**Closed by menakas** 2020-04-03 04:30 UTC
Labels: Priority: Low, [Type] Bug, [Type] Cannot reproduce
