### ISSUE TITLE
Smart Payment Buttons redirecting to PayPal upon payment failure

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-gateway-paypal-express-checkout#690] opened 2020-03-03 07:56 UTC
**Customer report**

19116825-hc Follow-up 2759826-zen

**Describe the bug**

If the first attempt to pay for an order fails via the smart payment button, the second attempt redirects you to PayPal instead of offering the payment form on the checkout page:

**To Reproduce**
1. Enable Smart payment button
2. Use wrong card details while trying to pay
3. Notice that it results in the following error:
    ![https://d.pr/i/cVUNHB+](https://d.pr/i/cVUNHB+)
4. *The notice itself is not accurate since the customer is already on the checkout page*
5. Attempt to pay again using the `Try again` button:
6. Notice that you're no longer using `Smart Payment button`
    ![https://d.pr/i/tsstzZ+](https://d.pr/i/tsstzZ+)

**Expected behavior**

1. Clear error notice on payment failure for the first time using Smart Payment buttons
2. Re-enable the form/payment via buttons instead of redirecting to PayPal

**Environment (please complete the following information):**
ANY

**Additional context**

If the redirection is by design, perhaps we could clearly state that in the initial error notice and let the customer know that they will be redirected upon trying to pay again? 🤔

---

Labels are assigned considering not all the customers would know more about the checkout process itself, and this may confuse them to the point where a sale is lost.

**Comment by mattallan** [comment] 2020-03-09 02:58
Hi @AashikP,

I'm able to reproduce the issues you've raised, however, I don't believe we can change this behaviour within our plugin.

The Credit Card payment flow (getting redirected to PayPal when clicking "try again") and the confusing error messages are both controlled by PayPal and I can't see any parameters or callbacks we can use in our render/payment request functions to change this behaviour.

Moving forward, I'll have to reach out to PayPal to confirm this is expected behaviour. I believe this is expected because their demo site also behaves in the same way as to what you're describing: https://developer.paypal.com/demo/checkout/#/pattern/server

> the second attempt redirects you to PayPal instead of offering the payment form on the checkout page

I'm going to remove the `[Type] Bug` label because I do believe it's working as intended (unless I'm mistaken)

**Comment by mattallan** [comment] 2020-03-10 02:44
I have reached out to PayPal and they've confirmed this is working as intended and not anything we can change from within our gateway plugin.

I would suggest contacting PayPal support directly as maybe they can tweak this on individual merchant accounts basis (not 100% certain on that though)

Closing this. Thanks @AashikP for the report! 😃

**Closed by mattallan** 2020-03-10 02:44 UTC
Labels: Many: M, Much: M, Priority: High
