### ISSUE TITLE
Getting First & Last name is a required field.

### ISSUE THREAD

**Issue by Provello** [woocommerce/woocommerce-gateway-paypal-express-checkout#742] opened 2020-05-26 08:52 UTC
### Describe the bug
When using PayPal button on Product or Cart after logging in to account, getting token and being redirected to checkout page ready to click Place Order to finalise order get 

Billing First name is a required field.
Billing Last name is a required field.

### To reproduce
1. Put item in cart
2. Press gold PayPal button
3. Login, pick payment method
4. get redirected
5. Click 'Place Order' at final steps 

**Screenshots**
https://i.imgur.com/rDbx3tC.png

### Expected behavior
Checkout to complete

**Environment (please complete the following information):**
 - WordPress Version 5.4.1
 - WooCommerce Version 4.1.1
 - PayPal (Express) Checkout Plugin Version 1.6.21
 - Browser [e.g. chrome, safari] Chrome Version 81.0.4044.138 (Official Build)
 - Any other plugins installed

Advanced Custom   Fields | 5.8.11
Autoptimize | 2.7.2
ClickToAddress Auto-Complete Integration | 1.1.11
Code Snippets | 2.14.0
Disable Comments | 1.10.2
Essential Grid | 2.3.6
Google Analytics for WordPress by   MonsterInsights | 7.10.4
Jetpack by WordPress.com | 8.5
Mobile Assistant Connector | 2.1.5
Popup Maker | 1.10.1
Post SMTP | 2.0.12
Really Simple SSL | 3.3.3
Redirection | 4.8
Slider Revolution | 6.1.6
Slider Revolution Typewriter Effect | 2.0.0
StorePep WooCommerce App Integration | 2.1.6
Variation Swatches for WooCommerce - Pro | 1.0.40
WebP Express | 0.17.3
WooCommerce | 4.1.1
WooCommerce Admin | 1.1.3
WooCommerce Checkout Field Editor | 1.5.26
WooCommerce Customer/Order/Coupon Export | 5.0.10
WooCommerce PayPal Checkout Gateway | 1.6.21
WooCommerce Smart Coupons | 4.7.1
Wordfence Security | 7.4.7
WP Rollback | 1.7.0
Yoast SEO Premium | 12.9.1

### Additional details

This was working fine say 2 days ago from posting time and date, we had updated to the latest major version 2.0.0 and 2.0.1 however it had broken payments beyond all repair for both Debit & Credit and PayPal checkouts using the plugin. Rolling back how restored Debit & Credit card payments through PayPal but not PayPal account payments.

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by Provello** [comment] 2020-05-26 09:47
Rolling back WooCommerce to previous version 4.1.0 seems to have fixed this, not ideal however a temporary solution

**Comment by mattallan** [comment] 2020-05-27 05:57
Hey @Provello,

Thanks for providing these extra details about your store and how to reproduce the problem. 

I'm unable to reproduce this issue on my own store using PayPal Checkout 1.6.21/2.0.1 and WooCommerce 4.1.1/4.1.0.

Based on the screenshot, there are a few possible causes here:
1. The billing first name and last name isn't properly being returned from PayPal
2. You have a third party plugin which is using custom first and last name checkout fields and it's not properly mapping the details from PayPal.

PayPal always require the first & last name fields to be filled in and you can't create a PayPal account without a first & last name, so to help us diagnose the problem:
 - Can you confirm the PayPal account you're logging into has both a first and last name set on the account?
 - Does the account have any special characters in the name that may be causing issues with it being sent back to your store, i.e. any symbols, numbers or international characters?
 - If you have a dev/staging site available for testing, can you confirm this is not plugin/theme conflict?

To rule out if this is a plugin/theme conflict, please deactivate all of your plugins except WooCommerce and PayPal Checkout and switch to a default/storefront theme and then test this again?

---

> we had updated to the latest major version 2.0.0 and 2.0.1 however it had broken payments beyond all repair for both Debit & Credit and PayPal checkouts using the plugin

Sorry about the troubles, can you please elaborate on this issue as well? Maybe create a new issue for this one.

**Comment by jorgeatorres** [comment] 2020-12-28 15:09
@Provello: Thanks again for your report. Given we weren't able to reproduce and also didn't receive answers to the questions above, I'm going to close this issue now. Feel free to re-open if you have additional details or if you're still having trouble with the plugin.

**Closed by jorgeatorres** 2020-12-28 15:09 UTC
Labels: status: needs author reply

**Comment by padcreative** [comment] 2021-01-05 13:22
We are having a similar recurring problem. Our site is connected to HotJar and we get feedback from some users (with a screengrab to prove it) that the site says "Billing Name is a Required Field". I've watched the recordings of these users via HotJar and they aren't dong anything unusual. The site takes a lot of orders and the vast majority are fine via PayPal, but this single issue keeps recurring. 

It's clear in the screengrabs that the billing first name is not missing. Each user has been unable to resolve this issue themselves.

As I cannot replicate it, it is difficult to resolve.

PLUGINS:
Query Monitor |   | by John Blackbourn – 3.6.5
Gravity Forms |   | by Gravity Forms – 2.4.21
Actionable Google Analytics |   | by Tatvic – CC-V3-3.6 – Installed version not tested with active version of WooCommerce 4.7.1
Advanced Custom Fields PRO |   | by Elliot Condon – 5.9.3
BackupBuddy |   | by iThemes – 8.6.2.0
CheckoutWC |   | by Objectiv – 3.13.3
Classic Editor |   | by WordPress Contributors – 1.6
Finale Lite - Sales Countdown Timer & Discount for WooCommerce |   | by XLPlugins – 2.13.0 – Installed version not tested with active version of WooCommerce 4.7.1
Free Gifts for WooCommerce |   | by FantasticPlugins – 5.9
Hotjar |   | by Hotjar – 1.0.9
Imsanity |   | by Exactly WWW – 2.7.1
Mailchimp for WooCommerce |   | by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.7.1
MailChimp |   | by MailChimp – 1.5.7
Manage Notification E-mails |   | by Virgial Berveling – 1.6.0
Post SMTP |   | by Yehuda Hassine – 2.0.15
Regenerate Thumbnails |   | by Alex Mills (Viper007Bond) – 3.1.4
User Switching |   | by John Blackbourn & contributors – 1.5.6
Product Feed PRO for WooCommerce |   | by AdTribes.io – 9.2.0
Print Invoice & Delivery Notes for WooCommerce |   | by Tyche Softwares – 4.6.1 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce PayPal Checkout Gateway |   | by WooCommerce – 2.1.1
WooCommerce SagePay Form and SagePay Direct Gateway |   | by Andrew Benbow – 4.5.0 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Product Recommendations |   | by SomewhereWarm – 1.4.7 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Sequential Order Numbers Pro |   | by SkyVerge – 1.15.3 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Wholesale Prices Premium |   | by Rymera Web Co – 1.25 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Wholesale Prices |   | by Rymera Web Co – 1.12.1 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce |   | by Automattic – 4.7.1 (update to version 4.8.0 is available)
Wordfence Security |   | by Wordfence – 7.4.14
Yoast SEO |   | by Team Yoast – 15.3
WP Realtime Sitemap |   | by Daniel Tweedy – 1.5.7
Yoast SEO: WooCommerce |   | by Team Yoast – 13.3 – Installed version not tested with active version of WooCommerce 4.7.1

**Comment by donmarkon** [comment] 2021-07-08 10:45
From time to time we get this error

![chrome_a32SYlNypX](https://user-images.githubusercontent.com/26697698/124909118-5ec14d80-dfea-11eb-9f02-dc763ed09bdc.jpg)
