### ISSUE TITLE
Strange behaviour on subscription auto renew order 

### ISSUE THREAD

**Issue by MasterNS** [woocommerce/woocommerce-gateway-paypal-express-checkout#591] opened 2019-07-22 05:45 UTC
This happens only on auto renew subscription orders (we have a Reference Transaction enabled).
Payment status is marked as completed, order status set as processing but "_cart_hash" is not created.
Client reported a problem, as for these orders they can't make a refunds.

Here are the last four lines from gateway log (I can provide a full log if needed):

07-04-2019 @ 19:52:31 - IPN request is valid according to PayPal.
07-04-2019 @ 19:52:31 - Found order #50148
07-04-2019 @ 19:52:31 - Payment status: completed
07-04-2019 @ 19:52:31 - Aborting, Invalid type:merch_pmt

**Comment by allendav** [comment] 2019-09-26 21:33
@LCmry - another one - is this likely a Subscription issue or in this plugin?

**Comment by LCmry** [comment] 2019-09-26 23:44
@allendav I think this plugin, Subscriptions has handlers for `merch_pmt` transaction types and it looks like for PPEC it's not an accepted type. https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-ipn-handler.php#L122

**Comment by james-allan** [comment] 2020-01-30 03:16
> Payment status is marked as completed, order status set as processing but "_cart_hash" is not created.

That is expected behaviour. Payment is complete/received, the order is set to processing. See [WC Order status explanations ](https://docs.woocommerce.com/document/managing-orders/) for more details.

`_cart_hash` is order meta that is only set if you purchase order through a cart/checkout. Because this is an automatic renewal, there is no cart hash value. 

> Client reported a problem, as for these orders they can't make a refunds.

I don't think any of those reasons would or should prevent merchants from making refunds. To test that I've tried to refund a renewal order and got the following error:

![Screen Shot 2020-01-30 at 1 10 35 pm](https://user-images.githubusercontent.com/8490476/73416866-ede02580-4361-11ea-8431-c22a0450dec4.png)

```
PHP Warning:  Illegal string offset 'refundable_txns' in /app/public/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec.php on line 371
PHP Warning:  Invalid argument supplied for foreach() in /app/public/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec.php on line 371
PHP Warning:  Illegal string offset 'refundable_txns' in /app/public/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec.php on line 395
PHP Notice:  Uninitialized string offset: 0 in /app/public/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec.php on line 395
PHP Warning:  Invalid argument supplied for foreach() in /app/public/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec.php on line 395
PHP Warning:  Illegal string offset 'refundable_txns' in /app/public/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec.php on line 420
```

Looking at the offending lines there is a lot of lines where we're expecting array keys to exist without checking first that the do. I think we just need to fix the `process_refund()` function.

**Comment by james-allan** [comment] 2020-01-30 03:33
So after a little more investigation, I think the problem comes from the fact that there are no `refundable_txns` set on the order when it is processed as an automatic renewal. `refundable_txns` is only set in the function `WC_Gateway_PPEC_Checkout_Handler::do_payment()` which is only called via the checkout. 

Processing a payment via `scheduled_subscription_payment()` => `do_reference_transaction()` => `_process_reference_transaction_response()` doesn't set the transaction ID as a refundable one.

**Comment by james-allan** [comment] 2020-01-30 04:42
Because of the direction this has gone, I'm closing this now in favour of #612. If there is another reason for not being able to process refunds because of missing cart hash meta or `Aborting, Invalid type:merch_pmt` errors feel free to reopen.

**Closed by james-allan** 2020-01-30 04:42 UTC
Labels: Priority: Low, [Type] Bug
