### ISSUE TITLE
Causes inability to Log In

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-paypal-express-checkout#464] opened 2018-08-05 16:26 UTC
Something to do with Smart buttons is causing this on the my account page:

>Notice: wp_woocommerce_session_66496d7a03c559d0fce4fdbe37392db8 cookie cannot be set - headers already sent by /home/imperial/public_html/wp-content/themes/storefront/header.php on line 10 in /home/imperial/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 835

(only if wp_debug is enabled).
Which, in turn, prevents users from logging in via the My Account page

This happens with Storefront theme active and all plugins except for WooCommerce and PayPal Checkout active.

I am not able to reproduce locally so suspect there may be some sort of server config causing it.

I added a ! is_account_page() conditional to this https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-cart-handler.php#L327 
to sort it on the user's site

**Note**: another work around would be to disable Smart Payment Buttons

ticket: 1298043-zen
1347145-zen

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://imperialhighlandsupplies.com
Site URL: https://imperialhighlandsupplies.com
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Unix) OpenSSL/1.0.1e-fips
PHP Version: 7.1.9 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 48 MB
PHP Time Limit: 60
PHP Max Input Vars: 1024
cURL Version: 7.29.0
NSS/3.28.4

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.30-MariaDB
Max Upload Size: 48 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 970.48MB
Database Data Size: 940.09MB
Database Index Size: 30.39MB
wp_woocommerce_sessions: Data: 852.68MB + Index: 23.66MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB
wp_woocommerce_order_itemmeta: Data: 0.12MB + Index: 0.04MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.02MB + Index: 0.02MB
wp_feeds: Data: 0.00MB + Index: 0.01MB
wp_gdpr_data_register: Data: 0.02MB + Index: 0.00MB
wp_gdpr_del_requests: Data: 0.02MB + Index: 0.00MB
wp_gdpr_log: Data: 60.58MB + Index: 0.00MB
wp_gdpr_requests: Data: 0.02MB + Index: 0.00MB
wp_grp_google_place: Data: 0.02MB + Index: 0.02MB
wp_grp_google_review: Data: 0.02MB + Index: 0.03MB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wp_itsec_logs: Data: 7.52MB + Index: 0.30MB
wp_itsec_temp: Data: 0.06MB + Index: 0.06MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 6.19MB + Index: 2.85MB
wp_postmeta: Data: 5.34MB + Index: 2.41MB
wp_posts: Data: 6.85MB + Index: 0.36MB
wp_smartiplog: Data: 0.02MB + Index: 0.00MB
wp_social_users: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.03MB + Index: 0.03MB
wp_terms: Data: 0.03MB + Index: 0.06MB
wp_term_relationships: Data: 0.09MB + Index: 0.18MB
wp_term_taxonomy: Data: 0.03MB + Index: 0.04MB
wp_usermeta: Data: 0.22MB + Index: 0.09MB
wp_users: Data: 0.01MB + Index: 0.01MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_wpmelon_advbedit_temp: Data: 0.02MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
wp_yith_ywpar_points_log: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.01MB
wp_ywf_user_fund_log: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 938
blocks: 3
customize_changeset: 161
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 169
page: 30
post: 17
product: 681
product_variation: 807
revision: 397
shop_coupon: 8
shop_order: 35
tm_global_cp: 25
wc_order_email: 4
wc_order_status: 9
wpcf7_contact_form: 2
yith-wccos-ostatus: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.1
WooCommerce: by Automattic – 3.4.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
ywf_deposit (ywf_deposit)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #11 - /shop/
Cart: #12 - /cart/
Checkout: #13 - /checkout/
My account: #14 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by harishankerr** [comment] 2018-08-05 17:03
Looks like a major problem, so bumping this to `Critical`. More reports of the issue here: https://wordpress.org/support/topic/causes-login-via-woocommerce-account-page-to-fail/

**Comment by jessepearson** [comment] 2018-08-14 20:52
The problem is here:
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/1.6.1/includes/class-wc-gateway-ppec-cart-handler.php#L336

This tries to set a cookie, however, `enqueue_scripts()` is called by the `wp_enqueue_scripts` action, which comes after `get_header`.

**Comment by jessepearson** [comment] 2018-08-14 20:54
Pinging @woocommerce/extendables to see if we can get some eyes on this. If Smart Payment Buttons are enabled, there's a cookie error that prevents things such as logging in and password resets.

**Comment by laurendavissmith** [comment] 2018-08-14 21:09
@dechov I'll take a look at this as well but would you have an idea why this might be happening?

**Comment by dechov** [comment] 2018-08-14 22:11
@laurendavissmith Thanks for the ping – I believe this may be fixed by https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/455 – trying to confirm now.

**Comment by dechov** [comment] 2018-08-14 22:18
Confirmed – reproduced the issue in 1.6.1, but seems to work fine in latest master, due to https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/455 addressing the issue as described in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/464#issuecomment-413012149.

As far as I can tell, this issue can be closed, and we should release ASAP.

**Comment by amandasjackson** [comment] 2018-08-15 13:40
adding another report of this issue via HC- customer is asking when the fix will be release as they require this plugin for sales

**Comment by laurendavissmith** [comment] 2018-08-15 13:41
@amandasjackson this should be fixed in master which was released an hour ago, https://woosupport.wordpress.com/2018/08/14/paypal-express-checkout-causing-login-password-reset-issues/#comment-13786

**Closed by laurendavissmith** 2018-08-15 13:41 UTC
Labels: [Pri] CRITICAL, [Type] Bug
