### ISSUE TITLE
Smart buttons not displayed correctly

### ISSUE THREAD

**Issue by noitrade99** [woocommerce/woocommerce-gateway-paypal-express-checkout#723] opened 2020-04-29 11:35 UTC
### Describe the bug
First of all, I would like to apologise if this is not a bug. I am new at this and my knowledge is very limited. I am currently trying to edit the way the PayPal smart buttons are displayed on my checkout page.

At the moment,on the checkout page, the button looks like this:

https://paste.pics/8T4MP

And I would like it to look like this ( to include the extra option to pay by Debit/Credit Card ).

https://paste.pics/8T4N1

How can I make it look like in the 2nd screenshot?.

### To reproduce

1. I tried all the different options however with no success.

**Environment (please complete the following information):**
 - WordPress Version 5.4
 - WooCommerce Version 4.0.1
 - PayPal (Express) Checkout Plugin Version  1.6.21
 - Browser [e.g. chrome, safari] and Version - Chrome 81.0.4044.122
 - Any other plugins installed - just a few basic ones

</details>

**Comment by jorgeatorres** [comment] 2020-04-29 13:55
Hi @noitrade99,

Thanks for getting in touch!

The look and feel you're referring to comes from an update PayPal released to their JS libraries in order to simplify and enhance the checkout experience. We've been working on adding support for these new features and plan to include it in the next version (see #668).

So, in short, it's not a bug: what you're seeing is just the "old" look and the new one will be available soon via a plugin update.

In the meantime, you can get a similar button display by enabling the "Vertical" button layout and making sure "Credit Card" is *not* listed in the "Hide funding methods" setting:

<img width="672" alt="Screen Shot 2020-04-29 at 10 49 14" src="https://user-images.githubusercontent.com/184724/80603715-28ac3500-8a07-11ea-8ba1-0702ce6edcca.png">

These settings would produce buttons that looks like this:

![Screen Shot on 2020-04-29 at 10-36-20](https://user-images.githubusercontent.com/184724/80603679-1e8a3680-8a07-11ea-8fa4-68c987d38018.png)

Make sure to enable this settings under "Button Settings" or under "Regular Checkout Button settings" if you have checkout-specific settings enabled.

Hope you find this information useful.

**Note:** I'm going to close this issue as it is not technically a bug. Feel free to comment if there's something I might've missed.

**Closed by jorgeatorres** 2020-04-29 13:55 UTC

**Comment by noitrade99** [comment] 2020-04-29 14:09
I find this information very useful.
Thank you for your comprehensive explanation and thank you for your time.
