### ISSUE TITLE
Cannot process refunds on "authorize" transactions

### ISSUE THREAD

**Issue by creativeround** [woocommerce/woocommerce-gateway-paypal-express-checkout#245] opened 2017-03-31 03:12 UTC
Authorize transactions never get their _woo_pp_txnData meta updated after capture action.

So process_refund() see's a blank array() for _woo_pp_txnData ($txn_data['refundable_txns']) and returns the error: "Refund Error: All transactions have been fully refunded. There is no amount left to refund"

FYI, I test this with a base theme and newest version of WordPress, WooCommerce and PayPal Express checkout (including the repo's master branch). Same issue happens.

Refunds work with "sale", but still get the same issue with "authorize".

Is the issue in this code logic?

Line 599 (class-wc-gateway-ppec-checkout-handler.php):

**Comment by creativeround** [comment] 2017-04-03 04:07
FYI,  I test this with a base theme and newest version of WordPress, WooCommerce and PayPal Express checkout (including the repo's master branch).  Same issue happens.

**Comment by bor0** [comment] 2017-06-05 08:34
Does it make sense to be able to refund authorization transactions?
@gedex / @hannahswain

**Comment by gedex** [comment] 2017-06-05 09:18
> Does it make sense to be able to refund authorization transactions?

I don't think we should support that. We should be able to refund once payment is received. See https://developer.paypal.com/docs/classic/api/merchant/RefundTransaction_API_Operation_NVP/.

@bor0 The fix is either:

* Store transaction ID, make sure to check if it's possible in the response. If there's no transaction ID at this point then leave it as is. Or,
* Better error message when transaction still in authorized.

**Comment by madeincosmos** [comment] 2017-06-05 12:07
As far as I understand, the problem occurs after the payment is eventually captured, so the refund should be possible at that time. Tried to reproduce it on my test site, but it seems sandbox and live modes work differently when it comes to Authorize action (see #260). 

It looks to me that we should probably focus on resolving #260 for now to make sure the Authorize action works 100% as intended, both in live mode and sandbox, and then come back to this issue and see what happens with refunds.

**Comment by gedex** [comment] 2017-06-05 12:15
> As far as I understand, the problem occurs after the payment is eventually captured, so the refund should be possible at that time

Right, store owner should be able to refund once captured. The culprit is transaction ID is not stored in the order meta when payment action is set to authorization hence I believe the fix is:

> Store transaction ID, make sure to check if it's possible in the response.

@bor0 I think it's around this [line](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-checkout-handler.php#L786-L801). Not sure if transaction ID exists at that point.

**Comment by creativeround** [comment] 2017-06-05 13:58
Just to clarify for everyone:

You should be able to cancel/void authorizations before its captured. <-- believe this works

You should be able to refund/partial refund authorizations once the authorization is captured. <-- doesn't work

**Closed** 2017-06-06 13:13 UTC
Labels: [Pri] High, [Status] Has PR, [Type] Bug
