### ISSUE TITLE
Live only - shipping address is empty

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-paypal-express-checkout#330] opened 2017-11-08 20:05 UTC
This is only occurring in live mode for some reason, so you'll need at least 2 live accounts for testing as PayPal will not allow merchants to purchase from themselves.  

When checking out with PayPal Express from the cart page, the problem occurs after returning to WooCommerce to confirm payment.  The shipping address is correctly passed through from PayPal and requests are sent to shipping methods like USPS and FedEx and rates are returned.  Then, a second request is sent to each shipping method that doesn't include the shipping address.  So, ultimately, no shipping methods can be found.  Both extensions return destination zip code errors such as `Missing value for ZipDestination.`.  

The shipping extensions used in my testing are: 

WooCommerce USPS Shipping
WooCommerce FedEx Shipping

@LaurenaRehbein @stevetested

**Comment by bor0** [comment] 2017-11-14 14:53
@mattyza is this a critical? Looks like high, as it's compatibility related.

**Comment by geeklore** [comment] 2017-11-15 17:25
ZD-773115 is asking about the status of this bug.

**Comment by mattyza** [comment] 2017-11-17 09:59
Agreed, @bor0.

That said, it seems quite high on the "high" list, as it's performing additional requests where not needed.

@mdmoore - is the second request overriding the first (valid) request? I ask, as that would bump this to critical for sure, if a customer was unable to checkout and have shipping rates.

**Comment by melindahelt** [comment] 2017-11-26 14:10
@bor0 @mattyza Customer checking in again and is very unhappy with the time taken on this.

Says:
>Seriously guys. SERIOUSLY? How high priority is this? The plugin IS BROKEN AND UNUSABLE with current Woocommerce. These is your OWN plugin! We can't keep having people checkout with no shipping method.

Any ETA on this...

**Comment by bor0** [comment] 2017-11-27 10:33
I wasn't able to reproduce this. If it only happens on live environment it will be tricky for me to reproduce.

As far as the severity of this issue:
1. It's a compatibility issue (if it turns out to be an issue at all)
2. Per "When checking out with PayPal Express from the cart page"
It seems a workaround until we resolve it is to use the following configuration:
[ ] Enable PayPal checkout on the cart page
[x] Enable the PayPal Mark on regular checkout

I wouldn't say the plugin is broken and unusable.

**Comment by melindahelt** [comment] 2017-11-27 13:23
@bor0 

>It's a compatibility issue (if it turns out to be an issue at all)

Compatibility issue with what? I'm new to this ticket, but it looks like standard plugin conflict tests were completed.

I'll pass along the workaround to the user now

**Comment by bor0** [comment] 2017-11-27 14:01
@melindahelt potential compat issue USPS/FedEx shipping extensions, although I wasn't able to reproduce.

**Comment by SiR-DanieL** [comment] 2017-12-04 05:40
@mattyza what are we gonna do with this? The customer is still unhappy and complaining, but @bor0 cannot reproduce the issue.

**Comment by masterbeat99** [comment] 2017-12-04 18:04
@SiR-DanieL , @bor0 , @melindahelt, @mattyza 

If you would all please pay attention to @mdmoore 's comment at the start of this thread, you CANNOT test this in sandbox mode.  the problem doesn't appear in sandbox mode and thats why you can't reproduce it.

If you turn off sandbox mode and use a live API (which is what happens in the REAL WORLD), then when a customer is returned from Paypal to the order review page where they should see shipping methods, you'll see the methods are returned for a split second and then vanish, like two calls are happening, so that in the end, all the customer sees is "no shipping methods avaialable" and they try to complete orders with us getting no shipping method, which is a huge problem.

Note this IS a compatibility issue - but it's YOUR compatibility issue - the plugin is not working as it should with YOUR WooCommerce and YOUR shipping plugins.  We went so far as to create a test server just for you to test, with nothing installed but Wordpress,  the default 2016 theme, Woocomerce, this plugin, and the shipping plugins, and the problem is easily reproducible.  This eliminates your ability to do the usual blame on another plugin or theme.  Sorry.   Moreover, we have the problem on about 17 different sites, across 4 servers and 3 different clients, all with different themes and plugins, so it's a little illogical to say the problem is only us when it happens on every site using the plugin.

The problem popped up with your latest updates to Woo core.  Before that the problem didn't exist.

TURN OFF SANDBOX AND USE A LIVE API.  You don't have to complete checkout and charge anything, you'll see it when you come back to the store.  And note @mdmoore  is correct, you need to use a Paypal account other than your own merchant account assigned to the store because Paypal prevents checkout from the same merchant account on the store, which further complicates your testing.

Please put a little effort into this, because every other 3rd party Paypal Express plugin is working fine (we had to switch), but yours doesn't.

**Comment by masterbeat99** [comment] 2017-12-04 18:07
It's kind of frustrating for @bor0  to simply reply "i wasn't able to reproduce this" when not doing what @mdmoore  clearly states at the top - that you have to test it in a live environment.  We started the whole ticket with the fact you can't reproduce in sandbox, so he can't reproduce it and removes himself for the issue?

**Comment by masterbeat99** [comment] 2017-12-04 18:20
@mdmoore , @SiR-DanieL @bor0 , @melindahelt  @mattyza  @LaurenaRehbein  @stevetested 

Also note that you cannot be logged in as admin to Wordpress dashboard to test, for some reason that inconsistently shows the problem and sometimes doesn't.  We agree with you it's hard to reproduce properly in a test environment, but the problem is it DOES exist in a live environment.

1.  Ensure you are using your Paypal Express plugin, without sandbox enabled, using real Paypal account/API as a live account environment.

2.  Ensure you are not logged into Wordpress as admin/user.

3.  Remove all the plugins you want to ensure your "compatibility issue" but make sure you have Woo, Paypal Express, and a couple shipping plugins - (we use your Fedex and your USPS).

4.  Add something to cart, from CART PAGE, hit the Paypal Express button.  Login to Paypal with a Paypal account, ensuring it's not the same account assigned to your test store, as Paypal forbids that.

5.  Authorize purchase on Paypal, return to store, you'll see the order review page where shipping methods should appear for customer to choose and then complete the order. Depending on the speed of your page refresh, server, etc - you'll possibly see the shipping methods appear for a brief second, and then disappear and end with result "no shipping methods available."   If you aren't paying attention, you'll miss the first list and just see the "no shipping methods available."     The incompatibility is something you guys changed in Woo core and how the shipping plugins are being called from order review.   Problem started after latest big update to Woo.

If you just read @mdmoore  start of the ticket above, he actually explained all of this to you right from the beginning, but frustratingly and typically, no one wants to follow the correct steps and instead just says "not reproducible" and here we are a month later with the same bug.

**Comment by bor0** [comment] 2017-12-04 19:53
In your reproduction steps you have:

> 4. Add something to cart, from CART PAGE, hit the Paypal Express button

In further isolating the issue, does the issue happen when you checkout from the checkout screen instead? (See https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/330#issuecomment-347141869 as a workaround until we find a fix)

**Comment by masterbeat99** [comment] 2017-12-05 10:54
@bor0 

The workaround is not a viable option for us or our clients.   When “pay with Paypal” is not enabled on the cart, our conversion rate drops 50%.   People don’t want to go to Checkout and fill in details to find Paypal as an option at the bottom.
 
There is a reason it (and your plugin) is called Paypal EXPRESS.

If you look at the very first comment from mdmoore at the top of Github, he perfectly recreated the issue and described how to recreate it.  We’ve found the bug on 17 installs.   Our developer in Australia confirmed the bug as well on his install.  IT EXISTS.   You have to follow my and mdmoore’s detailed explanation and you’ll reproduce it in 15 seconds.

Why are you insisting on recommending a “workaround” still 5 weeks later instead of actually taking a second to fix the bug?

Now let us ask you a quesiton.   Instead of arguing about "can't reproduce in test environment" and suggesting workarounds.  Have you actually taken the time to do what @mdmoore  did above and test it properly with LIVE API so that you can confirm what we, our clients, and our 3rd party developer all have discovered on a variety of installs?  That the bug EXISTS?

**Comment by mattyza** [comment] 2017-12-05 11:21
@masterbeat99 - Thank you for your detailed feedback on this.

I've adjusted the labels to indicate this is a critical issue, which is our top priority to resolve.

We'll report back here as soon as we have further findings from tests with live accounts.

cc @bor0 @mdmoore

**Comment by bor0** [comment] 2017-12-05 11:41
@masterbeat99, I never claimed the bug didn't exist, just that it's tricky for me to reproduce.

Let's keep the discussion here on a technical level, for the sake of easily resolving the issue.

**Comment by bor0** [comment] 2017-12-05 18:27
We spent quite some time PP-ing on this today together with @gedex. We may have found the culprit, but it seems it is a bit more complex than we thought, so I am hoping to continue tomorrow and possibly find a fix.

@masterbeat99, could you please try disabling geolocation in WooCommerce > Settings and let us know if that makes the issue go away? You can turn on geolocation again after.

This suggestion is just to confirm our assumptions, and knowing if it makes the error go away will be helpful for further investigation.

This eventually might turn out to be a WC core issue as well.

**Comment by masterbeat99** [comment] 2017-12-05 19:20
@bor0  Thanks bor.. trust me, i've tried to keep it at a technical level but you can imagine the trustration to check in on this ticket every week or so since it's original creation TWENTY SEVEN days ago (which was also another week after we first reported it) and to keep being told (as recently as my colorful commentary yesterday) by Automatic/Woocommerce support that "this is just you, only you, our developers can't reproduce it."  Frustrating after the loop of back and forth we were stuck in proving it existed even BEFORE mdmoore finally made this ticket!  Then only to go through 27 more days of "we can't reproduce" it is frustrating when both of us perfectly explained hot to reproduce it from the beginning.   Sorry, just got fed up of the runaround and no one wanting to dig in fix it.

We moved servers this last week and in that process I took down the test site/install I'd created just to prove this existed to everyone that had the bare minimum of core, Woo, and these plugins installed to ensure it wasn't our own compatibility.

Our live sites I finally had to give up on this getting resolved by you guys and installed the plugin from Angeleye which works fine.

So, unfortunately, no, I can't easily turn off Geo to continue to be the guinea pig.   But if you're testing and have reproduced it as it now appears you have, can't you do that test on your own?  Can we stop being the testers now and let you guys acknowlede the bug and fix it?

Appreciated!

**Closed** 2017-12-06 11:30 UTC
Labels: [Pri] CRITICAL, [Status] Has PR, [Type] Bug
