### ISSUE TITLE
Button size: value resets on settings change

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-paypal-express-checkout#424] opened 2018-06-08 12:07 UTC
1. Choose a size, i.e. `small`
2. Save the settings
3. Verify that the button size has indeed changed on the single product page
4. Note that the size setting is back to `responsive` 

Noted this on both on the global button settings and the single product settings. 

![Size](http://cld.wthms.co/7xIeGT+)
Full size: http://cld.wthms.co/7xIeGT

**Comment by dechov** [comment] 2018-06-14 22:37
Thanks! Fixed in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/409/commits/160045f9afb78700a30d7dcf1cc9eeaab08b163e.

The code that caused this was intended to change the value to "Responsive" (recommended value) when enabling SPB, and away from it when disabling SPB. The fix ensures it doesn't run on page load.

**Closed by dechov** 2018-06-14 22:37 UTC
