### ISSUE TITLE
Smart Payment Buttons not working on Cart page

### ISSUE THREAD

**Issue by philiprabbett** [woocommerce/woocommerce-gateway-paypal-express-checkout#581] opened 2019-06-10 10:24 UTC
I've done some debugging and it appears the registering of the script happens AFTER the script is attempted to be enqueued.

The following action fires first
`add_action( 'woocommerce_proceed_to_checkout', array( $this, 'display_paypal_button' ), 20 );`

This action fires AFTER the above however the above attempts to enqueue `wp_enqueue_script( 'wc-gateway-ppec-smart-payment-buttons' );`  while the below registers
`add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_scripts' ) );`

**Comment by reykjalin** [comment] 2019-09-27 06:54
It seems that the `paypalobjects.com/api/checkout.js` script has been deprecated and using the new script `paypal.com/sdk/js?client-id<client_id>` will render the Smart Buttons correctly and make them clickable instead of throwing an error.

@allendav should we open a new issue for updating the deprecated script?
cc @dechov

**Comment by dechov** [comment] 2019-10-01 04:47
In https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/491, we delayed the enqueuing of the scripts until they were needed. In my testing, the hooks fire in the proper order and the buttons appear on the Cart screen. I'm not sure under which circumstances the `woocommerce_proceed_to_checkout` action might fire prior to the `wp_enqueue_scripts` action so I wasn't able to reproduce this.

Not sure how best to solve short of reverting the aforementioned PR, but a workaround might be to also set a flag indicating the need to enqueue the script so that it can be enqueued in the `wp_enqueue_scripts` action if the need for it was already determined.

**Comment by allendav** [comment] 2019-10-02 21:08
@reykjalin wrote:

> @allendav should we open a new issue for updating the deprecated script?

Yes please. It looks like it includes buyer facing changes too (modal, not redirect) so let's plan this for a 1.7.0 release. If we can put that off until after the holidays, that would be great. Let me know if we can't reasonably control issues like this one without the new script and we can reconsider.

cc @bmccotter

**Comment by allendav** [comment] 2019-11-11 18:53
Moving this large-ish change to after the holidays

**Comment by ntsim** [comment] 2020-10-28 01:16
Been running into this problem when trying to use the Smart Payment buttons in v1.6 - v2.1. This is particularly problematic with v2+ as it seems like Smart Payment buttons are now mandatory, so this is basically preventing me from upgrading to v2.

I've spent a fair bit of time trying to figure this out, but have only really gotten as far as the reporter. 

Seems that the scripts hooked to `wp_enqueue_scripts` are only being registered __after__ the plugin has tried to render the buttons. This leads to the noop where `wp_enqueue_script('wc-gateway-ppec-smart-payment-buttons')` seems to do nothing. 

Having looked at the hook order with Query Monitor, it seems like all of the WooCommerce hooks well happen before `wp_enqueue_scripts`, which corresponds to what we're seeing. I'm no expert on WooCommerce, but it does seem like its actions are executed a tad bit too early in the WordPress lifecycle to make sense. Seems a bit strange to me, but maybe it's a problem with our setups somehow?

**Comment by jorgeatorres** [comment] 2020-10-28 15:22
Hi @ntsim!

I'm sorry you're having trouble with the plugin. Under normal circumstances, the `woocommerce_proceed_to_checkout` hook, which is the hook when we do the `wp_enqueue_script()` call you've mentioned, should happen much later during the page load process compared to `wp_enqueue_scripts`. This hook (`wp_enqueue_scripts`) should be fired by `wp_head()` which themes should (in theory) call before the content is generated (which is when the cart HTML is loaded, and thus the `woocommerce_proceed_to_checkout` hook fired).

That makes me think there might be something else going on here, probably the theme or another plugin is trying to "optimize" things by moving `wp_enqueue_scripts` to a later moment, after the content has been generated. Even if this is nonstandard, it'd be very useful to confirm if that's the case in order to workaround that in the plugin (if we can).

Could you please try to confirm whether this still occurs after deactivating other plugins (except WooCommerce and PayPal Checkout) or by temporarily changing your theme to a standard theme (Twenty Twenty, Storefront, etc.)?

**Comment by ntsim** [comment] 2020-10-30 10:52
Thanks for the great advice @jorgeatorres! I think I've figured out the root of the problem.

My specific theme is using Laravel's Blade templating engine to render out pages and we extend a parent layout template. Within our child template, we make a call to `woocommerce_before_main_content` to kick off WooCommerce. Unfortunately it seems like Blade renders out child templates before parent templates. meaning that the `woocommerce_before_main_content` was being executed before `wp_head` (in the parent template).

It doesn't seem like there is any way to make Blade defer rendering of the child template, so I've just gone with calling `wp_enqueue_scripts` within the child, but directly before `woocommerce_before_main_content`. Things seem to work! 

Of course, none of this is optimal as we're calling `wp_enqueue_scripts` twice. I don't know if there's much of a performance impact there. Don't know if you have any suggestions about a better approach?

**Comment by jorgeatorres** [comment] 2020-12-28 14:49
@ntsim: We might be able to dynamically load the buttons using JS in the near future, but right now we rely on hooks being fired in the "standard" order.
I'm glad you've found out a workaround and yes, while not optimal, it shouldn't have a noticeable impact in terms of performance as enqueued scripts are not enqueued again.

**Comment by jorgeatorres** [comment] 2020-12-28 14:50
Closing this issue as we've already migrated to the new SDK and current instances of this problem seem to be related to theme conflicts. We can look into loading the scripts and buttons "on demand" to help with this, but there's nothing incorrect with the current approach.

**Closed by jorgeatorres** 2020-12-28 14:50 UTC
Labels: feature: smart payment buttons, priority: high, type: bug
