### ISSUE TITLE
Tax not applied on the (Confirm your PayPal order) page at the checkout

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-paypal-express-checkout#433] opened 2018-06-27 13:46 UTC
#### Affected tickets

1243199-zen

#### What I expected

For the checkout to display accurate amount of what the customer is going to pay before they place the order.

#### What happens instead

After returning from PayPal, tax is not applied on the (Confirm your PayPal order) page at all. Only after someone places an order they can see how much they've actually paid.

#### Steps to reproduce

1. Set prices exclusive of tax, tax based on Customer shipping address,
2. Add the following tax rate:

![Screenshot](http://cld.wthms.co/TZ3Ht+)
Screenshot: http://cld.wthms.co/TZ3Ht

3. Create any taxable product, add it to cart, and click the PayPal button on the cart page,
4. Login with PayPal and set a shipping address in California on the PayPal account. You can use the following one as a test:

```
test buyer
1 Main st
San Jose, CA 95131
United States (US)
```

5. Observe there are no taxes applied on the confirmation page even though the shipping address is in the US:

![Screenshot](http://cld.wthms.co/SI1CKT+)
Screenshot: http://cld.wthms.co/SI1CKT

6. Place the order and observe the tax got eventually charged:

![Screenshot](http://cld.wthms.co/Oj8cP9+)
Screenshot: http://cld.wthms.co/Oj8cP9

**Comment by c-shultz** [comment] 2018-07-06 20:10
I was able to reproduce this.

One thing to note is that, if the customer provides an address for shipping calculation, then the tax will be added and included in confirmation:

<img width="411" alt="image" src="https://user-images.githubusercontent.com/6209518/42398032-0fb3ddd6-811d-11e8-9714-7e439b5b71f3.png">

Otherwise, it looks like the address is not being grabbed from PayPal and included in confirmation. I'll be on janitorial duties next week as well, so I'll work on stamping this out then.

**Comment by allendav** [comment] 2019-06-17 19:53
@c-shultz - looks like this was fixed. Closing it. If I shouldn't have, please re-open.

**Closed by allendav** 2019-06-17 19:53 UTC
Labels: [Pri] High, [Status] Has PR, [Type] Bug
