### ISSUE TITLE
Link PayPal account button not working

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/woocommerce-gateway-paypal-express-checkout#356] opened 2017-12-15 12:32 UTC
Reported in 824220-zen

Steps to reproduce:

- Go to PayPal Express settings
- Click the blue 'Setup or link an existing PayPal account' button.
- Log into PP and follow the instructions.

Once done, there is no indication (as far as I can tell) that the account is connected. The blue button is still there in the settings, and it lets you go through the whole process again.

It makes no difference if you're already logged into PayPal or not.

User reported that he was not able to accept payments until he entered his credentials manually.

@tommyshellberg confirmed:

> I can concur with this; the return URL is not set to the store. After linking a Live account, you will just stay in the PayPal dashboard, and if you return to your PPEC settings screen, it's not actually linked.

http://cld.wthms.co/DvU3Io

**Comment by bytesource** [comment] 2018-01-05 08:12
I cannot confirm this behavior (WooCommerce version 3.2.6, WordPress version 4.9.1)

**Comment by dechov** [comment] 2018-02-07 19:55
I and another member of my team have run into this issue, but after a change on the PayPal side, it now works well and AFAIK there should no longer be a problem.

**Comment by tommyshellberg** [comment] 2018-02-15 12:44
@danjjohnson can you retest this? That way we can close this out if it's working now.

**Comment by danjjohnson** [comment] 2018-02-21 13:35
Yes, it seems fine now. After logging into PayPal I see this:

![image](https://user-images.githubusercontent.com/1990037/36482688-0380c932-170c-11e8-834b-887dd2df4010.png)

Then I'm redirected back to my dashboard and can see my credentials there.

Closing this for now.

**Comment by jshiroma** [comment] 2018-03-22 19:17
I'm receiving this error at the moment. What were the changes in PayPal that were made to solve this issue?

**Comment by jshiroma** [comment] 2018-03-22 19:32
It managed to work. I just had to copy the redirect URL and paste it into a new tab. That did the trick.

**Comment by madeincosmos** [comment] 2018-04-12 09:04
Still reproducible with PPEC 1.5.3 & Woo 3.3.5, both in live and sandbox. I'm seeing the following errors in the console:

```
Refused to load the image 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pjxzdmcgd2lkdGg9IjI0cHgiIGhlaWdodD0iMjRweCIgdmlld0JveD0iMCAwIDI0IDI0IiB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPjxkZWZzPjxtYXNrIGlkPSJtIj48cmVjdCBmaWxsPSIjZmZmIiB4PSIwIiB5PSIwIiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHJ4PSI2IiByeT0iNiIvPjxyZWN0IGZpbGw9IiMwMDAiIHg9IjUiIHk9IjUiIHdpZHRoPSIxNCIgaGVpZ2h0PSIxNCIgcng9IjEiIHJ5PSIxIi8+PHJlY3QgZmlsbD0iIzAwMCIgeD0iMTAiIHk9IjAiIHdpZHRoPSI0IiBoZWlnaHQ9IjI0Ii8+PHJlY3QgZmlsbD0iIzAwMCIgeD0iMCIgeT0iMTAiIHdpZHRoPSIyNCIgaGVpZ2h0PSI0Ii8+PC9tYXNrPjwvZGVmcz48cmVjdCB4PSIwIiB5PSIwIiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiNmZmYiIG1hc2s9InVybCgjbSkiLz48L3N2Zz4=' because it violates the following Content Security Policy directive: "img-src *".
```

and then: 

```
Uncaught TypeError: t(...).selectpicker is not a function
```

![Screenshot](http://cld.wthms.co/m9bBts+)
Screenshot: http://cld.wthms.co/m9bBts

Copy-pasting redirect URL into a new window solves it temporarily.

**Comment by bor0** [comment] 2018-06-21 08:52
Not able to reproduce this. It might have been a temporary glitch on PP side. Feel free to re-open in case it still occurs.

**Closed by bor0** 2018-06-21 08:52 UTC
Labels: [Pri] High, [Type] Bug
