### ISSUE TITLE
PayPal checkout flow is different on single product

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-paypal-express-checkout#407] opened 2018-05-02 05:39 UTC
When the PayPal Express option `Checkout on Single Product` is enabled and the customer clicks "Pay with PayPal" on the single product page, the PayPal checkout flow is different than when clicking "Pay with PayPal" on the cart or checkout pages. 

Customer is redirected to PayPal when using checkout on single product pages:

![Redirected to PayPal](http://cld.wthms.co/4rtu04+)
Full size: http://cld.wthms.co/4rtu04

PayPal shows up in a modal on the cart:

![PayPal modal on cart](http://cld.wthms.co/q5ROGy+)
Full size: http://cld.wthms.co/q5ROGy

One of the users has pointed out this inconsistency and asks if we can make the single product page behave the same way as the cart / checkout pages.

Original issue: https://wordpress.org/support/topic/paypal-express-checkout-small-paypal-window-vs-large-paypal-window/

**Comment by hannahswain** [comment] 2018-05-08 11:52
CC: @roykho as the janitor for this week

**Comment by roykho** [comment] 2018-05-08 19:34
@bor0 would you happen to know the reason for this?

**Comment by bor0** [comment] 2018-05-09 07:14
I'd have to dig into it to recall, but as far as I remember I redirect to the cart screen with needed params.

Compare
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/2fee573e35d4a24e7c21fcb7a69ab7e75ed68bb6/includes/class-wc-gateway-ppec-cart-handler.php#L140
and
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/2fee573e35d4a24e7c21fcb7a69ab7e75ed68bb6/includes/class-wc-gateway-ppec-cart-handler.php#L171

**Comment by roykho** [comment] 2018-05-09 14:07
Ok after having looked more into this. Single product page is using the normal PPEC checkout and the cart page is using the "In-Context" PPEC checkout. There are logic specifically to use each method in different areas so that tells me it is not a bug but intentional. As far as why we did it this way is unknown. It would require significantly amount of changes to make them both work the same way though from initial examination. cc @laurendavissmith

**Comment by laurendavissmith** [comment] 2018-05-09 22:08
With this being an enhancement I don't think we should put any effort into this one yet

**Comment by laurendavissmith** [comment] 2018-06-19 20:46
Closing for now with the work being done for smart payment buttons

**Closed by laurendavissmith** 2018-06-19 20:46 UTC
Labels: [Pri] Low, [Type] Enhancement

**Comment by dechov** [comment] 2018-06-29 20:44
This is supported in 1.6 by Smart Payment Buttons (if enabled), which adds a JS integration to the single product page as well:

<img width="454" alt="screen shot 2018-06-05 at 7 36 50 pm" src="https://user-images.githubusercontent.com/1867547/42114018-80f508f6-7bbb-11e8-8a02-e4f053e08d6e.png">

Smart Payment Buttons are optional, but will become the only integration in the future (see https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/436).
