### ISSUE TITLE
Version 1.5.6 filters all address fields to "optional"

### ISSUE THREAD

**Issue by isaaclubow** [woocommerce/woocommerce-gateway-paypal-express-checkout#426] opened 2018-06-14 17:59 UTC
**Since 1.5.6, if "require billing address" setting is unchecked, it filters all address fields to "optional" even if the customer selects a different gateway. If the setting *is* checked, it seems to have no effect.**

In `class-wc-gateway-ppec-checkout-handler.php` the function `filter_default_address_fields()` seems to do this but it applies that filter to the fields *even if PPEC is not the selected gateway*. This is very heavy-handed because it makes all fields non-required, which causes validation errors for other payment processors. The issue can be prevented by `add_filter( 'woocommerce_paypal_express_checkout_address_not_required', '__return_false' );` but this shouldn't be necessary.

**Comment by Evakos** [comment] 2018-06-20 10:30
You have to set the phone field as required in the plugin otherwise the WC checkout field persists as optional. Is this the issue I'm seeing?

**Comment by isaaclubow** [comment] 2018-06-20 16:11
No. The plugin has a setting called "require billing address", and if it's unchecked, it filters *all* fields to "optional" even if the customer selects a different gateway. I'll update the OP, as I wasn't very clear.

**Comment by mikejolley** [comment] 2018-06-22 10:50
@bor0 @roykho This stops the core option to make phone required/optional from working too FYI

**Comment by bor0** [comment] 2018-06-22 11:16
cc @laurendavissmith for prioritization

**Comment by bondimedical3** [comment] 2018-06-22 11:31
Follow

**Comment by bor0** [comment] 2018-07-02 18:10
We need the code at https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/6efd1e5/includes/class-wc-gateway-ppec-checkout-handler.php#L123 to run only in case the current selected payment method is PPEC.

However, there doesn't seem to be a way to currently achieve this, given how WC core does not do any additional requests when you change a payment method:
![untitled12345](https://user-images.githubusercontent.com/1620929/42179365-f42b1908-7e33-11e8-894b-ea8c3a082699.gif)

**Comment by isaaclubow** [comment] 2018-07-03 16:46
Perhaps use Javascript...?

**Comment by bor0** [comment] 2018-07-04 11:48
@isaaclubow :) that is, of course, the obvious approach, however WooCommerce core does not seem to have something like that implemented at the moment.

cc @claudiulodro for any additional thoughts.

**Comment by claudiulodro** [comment] 2018-07-05 18:46
Not sure if I 100% follow what you are trying to do, but there is a [trigger fired when the selected payment method changes](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L119). You can maybe hook into that?

**Comment by bor0** [comment] 2018-07-05 21:14
@claudiulodro excellent, we can definitely re-use that. Would you know also if there's an ajax handler to which I can set requiredness of fields and update the checkout form dynamically?

**Comment by bor0** [comment] 2018-07-06 11:45
While working on another extension I found a similar approach used there.

Reference: https://github.com/woocommerce/woocommerce-account-funds/blob/878a363/assets/js/account-funds.js

**Comment by joelwills** [comment] 2018-07-20 17:21
Pinging @woocommerce/extendables As this is High Priority and has been open > one month. Thanks!

**Comment by joelwills** [comment] 2018-07-27 19:05
@bor0 This seems to be working in my testing. I'm not overly familiar with the options, but the Paypal buttons work on the Cart page and on the Checkout page the address fields are labeled required still. I would recommend someone else testing too.

Thanks!

**Comment by jobthomas** [comment] 2018-08-05 11:48
@woocommerce/extendables any updates on when this will be merged and deployed?

**Comment by amandasjackson** [comment] 2018-08-30 13:04
Adding another report of this 1381969-zen this is happening with their virtual products. Doesn't happen if PPEC is disabled.

**Comment by derekakelly** [comment] 2018-09-05 20:10
I found this issue while researching https://github.com/woocommerce/woocommerce/issues/20604

I was told there wasn't an easy fix to resolve this, short of removing the paypal plugin. I knew there had to be a work around and I found it in a plugin. I hope this will save some others the time of searching for a temporary solution.
https://wordpress.org/plugins/woo-phone-number-required/

**Comment by melindahelt** [comment] 2018-10-09 18:07
also in zd-1458734

@woocommerce/extendables any idea on this to set expectations?

**Comment by AashikP** [comment] 2018-10-31 06:46
@woocommerce/extendables Pinging here to update that the ticket is back on top of the queue. I do see that its a WIP. Is there an ETA we can provide to the customer to set expectations?

**Comment by fhaps** [comment] 2018-12-02 17:39
Another report of this in HC-5999210.

**Comment by hannahswain** [comment] 2018-12-08 10:20
Confirmed that the phone field is always optional when the PayPal Express Checkout plugin is enabled. This also can't be overridden using the Checkout Field Editor plugin. 

Reported via HC-8666514.

**Comment by davideprevosto** [comment] 2018-12-08 10:29
Hi there, 
maybe I found a quick way to workaround (just to fix the production issue I have with our customer):

`add_filter( 'woocommerce_billing_fields', function($address_fields) {
    $address_fields['billing_phone']['required'] = true;
    return $address_fields;
}, 10, 1 );`

**Comment by amandasjackson** [comment] 2019-01-30 15:22
Another user reported this again in HC 9969629

**Comment by keninbassart** [comment] 2019-02-12 18:26
1794459-zen User is reporting this issue as well.

**Comment by jobthomas** [comment] 2019-02-17 13:27
This might also be connected to #516

It also results in a conflict with Checkout Field Editor - see 1795513-zen

**Comment by treibalen** [comment] 2019-03-10 13:16
Also reported in 11094780-hc

**Comment by AashikP** [comment] 2019-05-22 06:25
Another report in 12945709-hc. Followup at 2050361-zen

**Comment by amitsharma1511** [comment] 2019-05-31 09:56
Any updates when this will be fixed ?

**Comment by nabrown** [comment] 2019-08-02 18:04
Seems like this issue has been lingering quite some time. @davideprevosto pointed me to a temporary workaround that I think is successful. The filter in the woocommerce plugin uses the `woocommerce_default_address_fields` hook, so you can override with your own filter:
```add_filter( 'woocommerce_default_address_fields', function($address_fields) {
	$address_fields['address_1']['required'] = true;
	$address_fields['city']['required'] = true;
	$address_fields['postcode']['required'] = true;
	$address_fields['country']['required'] = true;
	$address_fields['state']['required'] = true;
	return $address_fields;
}, 99, 1 );
```

I'm still testing the above but is seems to be working. If using the Paypal "Smart Payment Buttons" it does not complain that the above fields are required.

**Comment by justanotherentrepreneur** [comment] 2019-09-30 22:25
The First and Last Name fields are also optional for me. Are you able to provide the code to make these fields required as well? Thank you!

**Comment by AashikP** [comment] 2019-11-21 08:10
Possibly related: 2506001-zen

With `company` as a required field in the customizer:

![https://cld.wthms.co/Rkak6F+](https://cld.wthms.co/Rkak6F+)
*If the image does not load, please click this link: https://cld.wthms.co/Rkak6F*

Attempt to pay on the cart page:

![https://cld.wthms.co/OJasyv+](https://cld.wthms.co/OJasyv+)
*If the image does not load, please click this link: https://cld.wthms.co/OJasyv*

Complete the steps in PayPal and then when you're returned to checkout page, you cannot click the `Place order` button

![https://cld.wthms.co/6iI5n3+](https://cld.wthms.co/6iI5n3+)
*If the image does not load, please click this link: https://cld.wthms.co/6iI5n3*

**Comment by leigero** [comment] 2019-11-21 15:48
I first noticed this issue while using the checkout field editor plugin to ass a new field that was required. Customers were complaining about not being able to check out and not being able to enter the required information when I realized ti was a PayPal issue. After contacting the makers of that particular plugin, they pointed to this being an issue within the PayPal Checkout directly as this happens even with the "Company" field or any other field outside of the traditional address information PayPal typically provides.

**Comment by MarkCanada** [comment] 2019-11-22 06:09
The problem is in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout lines 131 to 138
```
		if ( method_exists( WC()->cart, 'needs_shipping' ) && ! WC()->cart->needs_shipping() && 'no' === wc_gateway_ppec()->settings->require_billing ) {
			$not_required_fields = array( 'first_name', 'last_name', 'company', 'address_1', 'address_2', 'city', 'postcode', 'country' );
			foreach ( $not_required_fields as $not_required_field ) {
				if ( array_key_exists( $not_required_field, $fields ) ) {
					$fields[ $not_required_field ]['required'] = false;
				}
			}
		}
```
This causes all these fields to be not required if neither shipping nor the "Require billing" is selected.
A payment plugin should not change required fields to be not required. It may set some to be required, but not the opposite.
I came across the issue when I noticed a sale with an IP address in our country and no contact information for a downloadable product. This resulted in WooCommerce not charging the required sales tax for that particular sale.
I have now used another plugin to add the required fields back in for now, but this shouldn't be needed.
If a business decides to not require fields that are required by default by WooCommerce, then a plugin can be used to not require the fields - but this current situation changes WooCommerce default behaviour and can result in required sales taxes not being charged on virtual products.

**Comment by gwegner** [comment] 2019-11-25 16:36
Same problem here. Plugin makes address fields optional, even if user checks out via other plugin. This enables the user to check out without providing an address. This violates European law.
Please fix asap!

**Comment by tinkertailordesign** [comment] 2019-11-25 16:39
Hi all,

I have been able to overcome this bug by using the "Reguire Billing Address" in the PayPay plugin settings. However you need to contact PayPal customer support to have this option switched on for your account at their end.

Thanks,
Luther

**Comment by gwegner** [comment] 2019-11-25 16:46
Thanks, I'll try to get this done. Still it should be fixed.

**Comment by tinkertailordesign** [comment] 2019-11-25 16:48
I agree!

**Comment by leigero** [comment] 2019-11-25 17:28
I require a unique property “t-shirt size” as all my products contain a shirt. I don’t think that’s something I can configure in PayPal so this still needs to be fixed for non-address related required fields.

**Comment by seanconklin** [comment] 2020-02-12 22:08
This is a real problem. I didn't realize PPEC was doing this until a new client signing up for their account told me so. This client called my checkout "misleading" since the other payment gateways do require the billing address. Then, I tried enabling the setting and I see PayPal wants me to call them to be able to turn on billing fields. Nope! Bye bye goes PPEC plugin on my site. Not worth confusing customers one bit.

**Closed** 2020-03-20 07:15 UTC
Labels: Many: L, Priority: High, [Type] Bug
