### ISSUE TITLE
Unable to change the "Billing address" text color in 'Debit or Credit Card' option

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce-gateway-paypal-express-checkout#827] opened 2020-10-16 17:19 UTC
### Describe the bug

I'm unsure if this is a bug or an enhancement, but we are unable to change the "Billing address" text in the payment field of the 'Debit or Credit Card' option during checkout: https://d.pr/i/TZpqYS

On dark backgrounds, this is very hard to see and doesn't follow certain accessibility guidelines. The problem, additionally, is that I'm unable to alter this with CSS since the form is loaded with JS after page load.

### To reproduce

1. Change background color of site to a dark color
1. Change any typography to a lighter color
1. Notice that you cannot change the 'Billing address' text color

**Screenshots**

![](https://d.pr/i/TZpqYS+)

### Expected behavior

Since a lot of themes/sites use a dark background, I'd expect to be able to change this text color somehow.

### Additional details

https://wordpress.org/support/topic/change-text-color-credit-card-options-dark-theme/

**Comment by jorgeatorres** [comment] 2020-10-16 18:31
Hi @jrick1229 👋 !

This seems to be a duplicate of #813. I'm closing in favor of that one, but feel free to re-open if you believe this is a different issue. That said, this looks like something PayPal needs to address in their JS SDK and not something we can fix on our end. We've reported this to PayPal (and they've opened an internal ticket) but we don't know much beyond that.

**Closed as completed by jorgeatorres** 2020-10-16 18:31 UTC

**Comment by jrick1229** [comment] 2020-10-16 18:33
Thanks @jorgeatorres! 😁 I was searching for "Billing address" to no avail, so that explains it. They are the same 👍
